def obtener_neurodesarrollo(años, meses):

    edad_meses = años * 12 + meses

    if edad_meses < 3:
        return """0-3M:
M. GRUESO: MUEVE SUS EXTREMIDADES: SI, SOSTIENE LA CABEZA: SI
M. FINO ADAPTATIVO: REACCIONA A LUZ Y SONIDOS: SI
AUDICIÓN Y LENGUAJE: LLORA PARA EXPRESAR NECESIDADES: SI
PERSONAL SOCIAL: SONRISA SOCIAL: SI"""

    elif edad_meses < 6:
        return """3-6M:
M. GRUESO: CONTROL DE CABEZA, SE VOLTEA: SI
M. FINO: PASA OBJETOS DE UNA MANO A OTRA: SI
LENGUAJE: BUSCA SONIDO: SI
SOCIAL: RÍE A CARCAJADAS: SI"""

    elif edad_meses < 9:
        return """6-9M:
M. GRUESO: SE SIENTA SIN APOYO: SI
M. FINO: PINZA DIGITAL: SI
LENGUAJE: ATIENE CONVERSACIÓN: SI
SOCIAL: REACCIONA A EXTRAÑOS: SI"""

    elif edad_meses < 12:
        return """9-12M:
M. GRUESO: GATEA, SE PONE DE PIE: SI
LENGUAJE: DICE "NO": SI
SOCIAL: JUEGA ACTIVAMENTE: SI"""

    elif edad_meses < 18:
        return """12-18M:
M. GRUESO: CAMINA SOLO: SI
LENGUAJE: USA PALABRAS: SI
SOCIAL: SEÑALA PARTES DEL CUERPO: SI"""

    elif edad_meses < 24:
        return """18-24M:
M. GRUESO: CORRE: SI
LENGUAJE: USA FRASES DE 2 PALABRAS: SI
M. FINO: GARABATEA: SI"""

    elif edad_meses < 36:
        return """2-3 AÑOS:
M. GRUESO: SUBE ESCALONES: SI
LENGUAJE: DICE SU NOMBRE: SI
SOCIAL: INTERACCIÓN ADECUADA: SI"""

    elif edad_meses < 48:
        return """3-4 AÑOS:
M. GRUESO: CAMINA EN PUNTAS: SI
M. FINO: COPIA CÍRCULO: SI
SOCIAL: JUEGA CON OTROS: SI"""

    elif edad_meses < 60:
        return """4-5 AÑOS:
COGNITIVO: RECONOCE COLORES: SI
AUTONOMÍA: SE VISTE SOLO: SI
SOCIAL: PROPONE JUEGOS: SI"""

    # 🔥 NUEVO BLOQUE ESCOLAR

    elif edad_meses < 84:
        return """5-7 AÑOS:
COGNITIVO: APRENDIZAJE ACORDE A LA EDAD: SI
LENGUAJE: EXPRESIÓN VERBAL ADECUADA: SI
ATENCIÓN: ADECUADA: SI
SOCIAL: INTERACCIÓN CON PARES ADECUADA: SI"""

    elif edad_meses < 120:
        return """7-10 AÑOS:
COGNITIVO: RENDIMIENTO ESCOLAR ADECUADO: SI
LENGUAJE: COMPRENSIÓN Y EXPRESIÓN ADECUADAS: SI
ATENCIÓN: CONSERVADA: SI
CONDUCTA: ADECUADA: SI"""

    elif edad_meses < 144:
        return """10-12 AÑOS:
COGNITIVO: PENSAMIENTO LÓGICO ACORDE: SI
ESCOLARIDAD: ADECUADA: SI
ATENCIÓN: ADECUADA: SI
SOCIAL: RELACIONES INTERPERSONALES ADECUADAS: SI"""

    elif edad_meses < 180:
        return """12-15 AÑOS:
COGNITIVO: FUNCIONES EJECUTIVAS ADECUADAS: SI
CONDUCTA: SIN ALTERACIONES: SI
SOCIAL: ADECUADA INTEGRACIÓN SOCIAL: SI
EMOCIONAL: ESTABLE: SI"""

    else:
        return """15-18 AÑOS:
COGNITIVO: PENSAMIENTO ABSTRACTO CONSERVADO: SI
CONDUCTA: ADECUADA: SI
SOCIAL: INTERACCIÓN SOCIAL ADECUADA: SI
EMOCIONAL: SIN ALTERACIONES REFERIDAS: SI"""