"""Casos docentes editables para documentar rutas pediátricas frecuentes.

Los ejemplos no sustituyen la valoración ni los protocolos institucionales. Se
cargan como punto de partida para que el profesional los adapte al paciente.
"""

from __future__ import annotations

from copy import deepcopy
from datetime import date


ANTECEDENTES_PEDIATRICOS = """NEONATALES: PRODUCTO DE SEGUNDA GESTACIÓN, EMBARAZO CONTROLADO, SIN COMPLICACIONES, NACE A TÉRMINO, SIN REQUERIMIENTO DE OXÍGENO U HOSPITALIZACIÓN, EGRESO CONJUNTO.
INMUNOLÓGICOS: VACUNAS AL DÍA SEGÚN PAI, SIN REACCIONES ATRIBUIDAS A VACUNAS.
ALIMENTACIÓN: ACORDE A LA EDAD.
PATOLÓGICOS, HOSPITALARIOS, FARMACOLÓGICOS, TRAUMÁTICOS, TÓXICOS, ALÉRGICOS, TRANSFUSIONALES Y QUIRÚRGICOS: NIEGA.
FAMILIARES: PADRE Y MADRE SANOS, NO CONSANGUÍNEOS.
PSICOSOCIALES: VIVIENDA CON TODOS LOS SERVICIOS, SIN EXPOSICIONES DE RIESGO RELEVANTES."""

REVISION_PEDIATRICA_COMPLETA = """CONSTITUCIONAL: SEGÚN CUADRO ACTUAL; SIN PÉRDIDA DE PESO DOCUMENTADA.
CARDIOVASCULAR: NIEGA CIANOSIS, SÍNCOPE, DOLOR PRECORDIAL O EDEMAS.
RESPIRATORIO: SÍNTOMAS Y HALLAZGOS DESCRITOS EN ENFERMEDAD ACTUAL Y EXAMEN FÍSICO; NIEGA APNEAS Y CIANOSIS.
DIGESTIVO: SEGÚN CUADRO ACTUAL; NIEGA HEMATEMESIS, HEMATOQUEZIA O MELENA.
URINARIO: DIURESIS SEGÚN CUADRO ACTUAL; NIEGA DISURIA, HEMATURIA O COLURIA.
NEUROLÓGICO: NIEGA CONVULSIONES, ALTERACIÓN DEL ESTADO DE CONCIENCIA O FOCALIZACIONES.
PIEL: NIEGA PETEQUIAS, EQUIMOSIS O LESIONES DIFERENTES A LAS DESCRITAS.
MÚSCULO-ESQUELÉTICO: NIEGA ARTRALGIAS, COJERA O EDEMAS."""


def _examen_pediatrico_completo(
    estado, *, nariz="PERMEABLE, SIN SECRECIONES.",
    orofaringe="MUCOSAS HÚMEDAS, SIN LESIONES.",
    torax="SIMÉTRICO, NORMOEXPANSIBLE, SIN TIRAJES.",
    cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN AGREGADOS PULMONARES.",
    abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, NO DOLOROSO, SIN SIGNOS DE IRRITACIÓN PERITONEAL.",
    piel="ROSADA, BIEN PERFUNDIDA, SIN LESIONES.",
):
    """Mantiene el examen por sistemas completo en cada caso docente."""
    return f"""{estado}

CABEZA: NORMOCÉFALA, SIN LESIONES.
OJOS: CONJUNTIVAS ROSADAS, ESCLERAS ANICTÉRICAS, PUPILAS ISOCÓRICAS Y REACTIVAS.
OÍDOS: SIN ALTERACIONES EVIDENTES.
NARIZ: {nariz}
OROFARINGE: {orofaringe}
CUELLO: MÓVIL, SIN ADENOPATÍAS.
TÓRAX: {torax}
CARDIOPULMONAR: {cardiopulmonar}
ABDOMEN: {abdomen}
GENITALES: ACORDES A LA EDAD, SIN ALTERACIONES EVIDENTES.
EXTREMIDADES: EUTRÓFICAS, SIMÉTRICAS, SIN EDEMAS, LLENADO CAPILAR MENOR DE 2 SEGUNDOS.
NEUROLÓGICO: ALERTA, SIN FOCALIZACIONES, SIN SIGNOS DE MENINGISMO, FUERZA Y TONO CONSERVADOS, SIN DÉFICIT.
PIEL: {piel}"""


def _caso(
    *, nombre, motivo, enfermedad, examen, diagnostico, busqueda, conducta,
    plan, signos, gpc="", aiepi="RESPIRATORIO", gpc_criterios=None,
    aiepi_criterios=None, antecedentes=ANTECEDENTES_PEDIATRICOS,
    revision=REVISION_PEDIATRICA_COMPLETA,
    fecha_nacimiento=date(2023, 1, 15), sexo="Femenino", justificacion="",
):
    cierres = {
        "EGRESO": (
            "POR EL ESTADO GENERAL CONSERVADO, LA ESTABILIDAD CLÍNICA Y LA "
            "AUSENCIA DE CRITERIOS ACTUALES DE HOSPITALIZACIÓN, SE DEFINE MANEJO "
            "AMBULATORIO. SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE LAS MEDIDAS EN CASA, EL TRATAMIENTO "
            "INDICADO, LOS SIGNOS DE ALARMA Y LA OPORTUNIDAD DE RECONSULTA."
        ),
        "OBSERVACIÓN": (
            "SE DEFINE OBSERVACIÓN PEDIÁTRICA PARA VIGILANCIA CLÍNICA SERIADA, "
            "OBJETIVAR LA RESPUESTA AL MANEJO INICIAL Y REEVALUAR EL SITIO DE MANEJO. "
            "SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE EL MOTIVO DE LA OBSERVACIÓN, LOS HALLAZGOS A VIGILAR "
            "Y EL PLAN DE REVALORACIÓN."
        ),
        "HOSPITALIZACIÓN": (
            "POR LOS HALLAZGOS CLÍNICOS DESCRITOS Y EL RIESGO DE DETERIORO, SE JUSTIFICA "
            "HOSPITALIZACIÓN PEDIÁTRICA PARA TRATAMIENTO, MONITORIZACIÓN Y REVALORACIÓN "
            "CLÍNICA. SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE LA INDICACIÓN, EL PLAN TERAPÉUTICO Y LOS "
            "CRITERIOS DE EVOLUCIÓN."
        ),
    }
    analisis = (
        f"PACIENTE PEDIÁTRICO QUE CONSULTA POR {motivo}. {enfermedad} "
        f"{justificacion or 'LA VALORACIÓN CLÍNICA SE INTERPRETA EN CONJUNTO CON LOS SIGNOS VITALES, EL EXAMEN POR SISTEMAS Y LA EVOLUCIÓN.'} "
        f"{cierres.get(conducta, '')}"
    )
    return {
        "nombre": nombre,
        "fecha_nacimiento": fecha_nacimiento,
        "sexo": sexo,
        "motivo": motivo,
        "enfermedad": enfermedad,
        "antecedentes": antecedentes,
        "revision": revision,
        "examen": examen,
        "diagnostico": diagnostico,
        "busqueda_cie10": busqueda,
        "conducta": conducta,
        "plan": plan,
        "analisis": analisis,
        "signos": signos,
        "gpc": gpc,
        "aiepi": aiepi,
        "gpc_criterios": gpc_criterios or {},
        "aiepi_criterios": aiepi_criterios or {},
    }


EJEMPLOS_PEDIATRIA = {
    "IRA alta / rinofaringitis": _caso(
        nombre="IRA ALTA - MANEJO AMBULATORIO",
        motivo="FIEBRE Y TOS",
        enfermedad="CUADRO CLÍNICO DE 3 DÍAS DE EVOLUCIÓN CON TOS HÚMEDA, RINORREA HIALINA Y FIEBRE NO CUANTIFICADA, SIN PICO TÉRMICO DOCUMENTADO. MANTIENE BUEN ESTADO GENERAL, TOLERA VÍA ORAL Y PRESENTA DIURESIS CONSERVADA. NIEGA DIFICULTAD RESPIRATORIA, TIRAJE, RESPIRACIÓN RÁPIDA, CIANOSIS, APNEAS, ESTRIDOR, SIBILANCIAS, VÓMITO, DIARREA, CONVULSIONES O SOMNOLENCIA ANORMAL. SIN CONTACTO CON PACIENTES GRAVES; VACUNACIÓN AL DÍA SEGÚN REFIERE.",
        examen=_examen_pediatrico_completo(
            "PACIENTE EN BUEN ESTADO GENERAL, ALERTA, HIDRATADO, FEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            nariz="RINORREA HIALINA ESCASA, SIN ALETEO NASAL.",
            orofaringe="MUCOSAS HÚMEDAS, FARINGE LEVEMENTE ERITEMATOSA, SIN EXUDADO.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN SIBILANCIAS, ESTERTORES NI DIFICULTAD RESPIRATORIA.",
        ),
        diagnostico="J00 - NASOFARINGITIS AGUDA [RESFRIADO COMÚN]",
        busqueda="rinofaringitis aguda",
        conducta="EGRESO",
        plan="""{LINEA_ACETAMINOFEN}
- LAVADOS NASALES CON SOLUCIÓN SALINA Y ADECUADA HIDRATACIÓN ORAL.
- SE BRINDA EDUCACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA RESPIRATORIOS, TOLERANCIA ORAL Y RECONSULTA.
- CONTROL POR PEDIATRÍA SEGÚN EVOLUCIÓN.""",
        signos={"ta": "90/55", "fc": "110", "fr": "24", "sat": "97", "temp": "38.1", "peso": "16.2", "talla": "101", "pc": "50.5", "pb": "16"},
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 24 RPM, SIN DIFICULTAD RESPIRATORIA.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "AUSENTES.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 97% AL AIRE AMBIENTE; BUEN ESTADO GENERAL.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "IRA ALTA SIN SIGNOS DE GRAVEDAD; MANEJO AMBULATORIO; SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA.",
        },
    ),
    "Neumonía no complicada - ambulatoria": _caso(
        nombre="NEUMONÍA NO COMPLICADA - MANEJO AMBULATORIO",
        motivo="TOS Y FIEBRE",
        enfermedad="CUADRO CLÍNICO DE 4 DÍAS DE EVOLUCIÓN CON TOS HÚMEDA, FIEBRE CUANTIFICADA HASTA 38.5 °C Y DISMINUCIÓN LEVE DEL APETITO. TOLERA VÍA ORAL, MANTIENE DIURESIS Y JUEGO ENTRE LOS PICOS FEBRILES. NIEGA RESPIRACIÓN RÁPIDA, TIRAJE, CIANOSIS, APNEAS, ESTRIDOR, SIBILANCIAS, VÓMITO DE TODO LO INGERIDO, CONVULSIONES O LETARGIA. SIN ANTIBIÓTICOS PREVIOS PARA EL CUADRO ACTUAL.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADO, FEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            nariz="PERMEABLE, CON RINORREA HIALINA ESCASA.",
            orofaringe="MUCOSAS HÚMEDAS, SIN EXUDADO.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR LEVEMENTE DISMINUIDO EN BASE DERECHA CON CREPITANTES FOCALES, SIN TIRAJES, CIANOSIS NI SIBILANCIAS.",
        ),
        diagnostico="J18 - NEUMONÍA, NO ESPECIFICADA",
        busqueda="neumonía",
        conducta="EGRESO",
        plan="""{LINEA_AMOXICILINA}
{LINEA_ACETAMINOFEN}
- CONTROL CLÍNICO EN 48 A 72 HORAS O ANTES SI DETERIORO.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA RESPIRATORIOS Y DE RECONSULTA.""",
        signos={"ta": "92/56", "fc": "118", "fr": "38", "sat": "96", "temp": "38.4", "peso": "14", "talla": "96", "pc": "49", "pb": "15.5"},
        gpc="NEUMONIA",
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "SIN TIRAJES, SIN CIANOSIS, ESTADO GENERAL CONSERVADO.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 96% AL AIRE AMBIENTE.",
            "DECISIÓN DE SITIO DE MANEJO": "MANEJO AMBULATORIO: TOLERA VÍA ORAL, SIN SIGNOS DE GRAVEDAD.",
            "SIGNOS DE ALARMA / CONTROL": "CONTROL EN 48-72 HORAS; SE INDICA RECONSULTAR POR TIRAJE, CIANOSIS, DETERIORO, INTOLERANCIA ORAL O PERSISTENCIA DE FIEBRE.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 38 RPM, SIN TIRAJES.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIN TIRAJE, ESTRIDOR NI SIBILANCIAS.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 96% AL AIRE AMBIENTE; PERFUSIÓN Y ESTADO GENERAL CONSERVADOS.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "NEUMONÍA SIN CRITERIOS CLÍNICOS DE GRAVEDAD; EGRESO CON ANTIBIÓTICO, CONTROL Y SIGNOS DE ALARMA.",
        },
    ),
    "Neumonía - hospitalización": _caso(
        nombre="NEUMONÍA CON CRITERIOS DE HOSPITALIZACIÓN",
        motivo="TOS, FIEBRE Y DIFICULTAD RESPIRATORIA",
        enfermedad="CUADRO DE 3 DÍAS DE EVOLUCIÓN CON FIEBRE HASTA 39 °C, TOS PRODUCTIVA Y AUMENTO PROGRESIVO DEL TRABAJO RESPIRATORIO. CUIDADOR REFIERE DISMINUCIÓN DE LA INGESTA ORAL Y DIURESIS MENOR A LA HABITUAL. NIEGA CONVULSIONES, LETARGIA, APNEAS Y CIANOSIS CENTRAL. SIN ASPIRACIÓN, TRAUMA NI INGESTA DE CUERPO EXTRAÑO. SE DOCUMENTA ESTADO VACUNAL Y TRATAMIENTO RECIBIDO PREVIO A LA CONSULTA.",
        examen=_examen_pediatrico_completo(
            "PACIENTE IRRITABLE, ALERTA, TAQUIPNEICO, CON HIDRATACIÓN LEVEMENTE DISMINUIDA Y FIEBRE.",
            nariz="PERMEABLE, SIN ALETEO NASAL MARCADO.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL LEVE A MODERADO.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR DISMINUIDO EN BASE IZQUIERDA CON CREPITANTES, SIN CIANOSIS CENTRAL.",
            piel="BIEN PERFUNDIDA, SIN PETEQUIAS NI EXANTEMA.",
        ),
        diagnostico="J18 - NEUMONÍA, NO ESPECIFICADA",
        busqueda="neumonía",
        conducta="HOSPITALIZACIÓN",
        plan="""- HOSPITALIZACIÓN PEDIÁTRICA Y VIGILANCIA CLÍNICA RESPIRATORIA.
- ACCESO VENOSO PERIFÉRICO, DIETA ACORDE A LA EDAD SEGÚN TOLERANCIA Y VIGILANCIA DE INGESTA/DIURESIS.
- OXÍGENO SI REQUIERE, CON META DE SATURACIÓN SEGÚN ALTITUD Y PROTOCOLO INSTITUCIONAL.
{LINEA_PENICILINA_CRISTALINA}
{LINEA_ACETAMINOFEN}
- HIGIENE NASAL Y TERAPIA RESPIRATORIA SEGÚN NECESIDAD CLÍNICA.
- CONTROL DE SIGNOS VITALES, TRABAJO RESPIRATORIO, TOLERANCIA ORAL, HIDRATACIÓN Y DIURESIS; AVISAR CAMBIOS.
- RADIOGRAFÍA DE TÓRAX Y PARACLÍNICOS DE EXTENSIÓN SEGÚN SEVERIDAD, EVOLUCIÓN Y DISPONIBILIDAD; DOCUMENTAR LA JUSTIFICACIÓN.""",
        signos={"ta": "88/52", "fc": "132", "fr": "48", "sat": "91", "temp": "39", "peso": "12", "talla": "90", "pc": "48", "pb": "14.5"},
        gpc="NEUMONIA",
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "TAQUIPNEA Y TIRAJE SUBCOSTAL; DISMINUCIÓN DE INGESTA ORAL.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 91% AL AIRE AMBIENTE.",
            "DECISIÓN DE SITIO DE MANEJO": "HOSPITALIZACIÓN POR COMPROMISO RESPIRATORIO E INTOLERANCIA RELATIVA A LA VÍA ORAL.",
            "SIGNOS DE ALARMA / CONTROL": "VIGILANCIA INTRAHOSPITALARIA, REVALORACIÓN RESPIRATORIA Y DE OXIGENACIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "NO CONVULSIONES NI LETARGIA; INGESTA DISMINUIDA.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 48 RPM CON TIRAJE SUBCOSTAL.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "TIRAJE SUBCOSTAL PRESENTE; SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 91% AL AIRE AMBIENTE; REQUIERE VIGILANCIA Y OXÍGENO SEGÚN RESPUESTA.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "MANEJO INTRAHOSPITALARIO POR CRITERIOS CLÍNICOS DE GRAVEDAD.",
        },
        justificacion="PRESENTA TAQUIPNEA, TIRAJE SUBCOSTAL, SATURACIÓN DE 91% AL AIRE AMBIENTE, DISMINUCIÓN DE LA INGESTA Y HALLAZGOS FOCALES PULMONARES, COMPATIBLES CON COMPROMISO RESPIRATORIO QUE REQUIERE MANEJO INTRAHOSPITALARIO.",
    ),
    "Bronquiolitis": _caso(
        nombre="BRONQUIOLITIS - OBSERVACIÓN",
        motivo="TOS Y RESPIRACIÓN RUIDOSA",
        enfermedad="LACTANTE DE 8 MESES CON 3 DÍAS DE CORIZA, RINORREA Y TOS, SEGUIDOS DE RESPIRACIÓN RUIDOSA. ES EL PRIMER EPISODIO SIBILANTE. LACTANCIA DISMINUIDA, PERO ACEPTA PEQUEÑAS TOMAS; DIURESIS PRESENTE, AUNQUE MENOR A LA HABITUAL. NIEGA APNEAS, CIANOSIS, LETARGIA, CONVULSIONES Y VÓMITO DE TODO LO INGERIDO. SIN ANTECEDENTE DE CARDIOPATÍA, DISPLASIA BRONCOPULMONAR, INMUNODEFICIENCIA O PREMATURIDAD DE ALTO RIESGO.",
        examen=_examen_pediatrico_completo(
            "LACTANTE ALERTA, REACTIVO, CON HIDRATACIÓN LEVEMENTE DISMINUIDA, AFEBRIL.",
            nariz="RINORREA HIALINA Y CONGESTIÓN NASAL.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL LEVE Y ESPIRACIÓN PROLONGADA.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR BILATERAL, CON SIBILANCIAS DIFUSAS, SIN CIANOSIS.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, NO DOLOROSO.",
        ),
        diagnostico="J21 - BRONQUIOLITIS AGUDA",
        busqueda="bronquiolitis",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y REVALORACIÓN CLÍNICA RESPIRATORIA.
- HIGIENE NASAL, OFRECER LÍQUIDOS O LACTANCIA FRACCIONADA Y VIGILAR DIURESIS.
- OXÍGENO SEGÚN SATURACIÓN, ALTITUD Y PROTOCOLO INSTITUCIONAL.
- NO INDICAR ANTIBIÓTICOS, BRONCODILATADORES O PARACLÍNICOS DE RUTINA SIN JUSTIFICACIÓN CLÍNICA.
- EDUCACIÓN DE SIGNOS DE ALARMA Y DEFINICIÓN DEL SITIO DE MANEJO SEGÚN REVALORACIÓN.""",
        signos={"ta": "", "fc": "138", "fr": "44", "sat": "92", "temp": "37.8", "peso": "8", "talla": "69", "pc": "44", "pb": "14"},
        gpc="BRONQUIOLITIS",
        fecha_nacimiento=date(2025, 12, 20),
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "TIRAJE SUBCOSTAL LEVE Y SIBILANCIAS; SIN APNEAS NI CIANOSIS.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 92% AL AIRE AMBIENTE.",
            "HIDRATACIÓN / TOLERANCIA ORAL": "LACTANCIA DISMINUIDA, ACEPTA PEQUEÑAS TOMAS; DIURESIS EN VIGILANCIA.",
            "SIGNOS DE ALARMA / RECONSULTA": "REVALORAR TRABAJO RESPIRATORIO, SATURACIÓN, INGESTA Y DIURESIS PARA DEFINIR EGRESO U HOSPITALIZACIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES; SIN APNEAS NI CIANOSIS.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 44 RPM, TIRAJE SUBCOSTAL LEVE.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "TIRAJE SUBCOSTAL LEVE Y SIBILANCIAS DIFUSAS; SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 92% AL AIRE AMBIENTE; REQUIERE OBSERVACIÓN Y REVALORACIÓN.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN POR TRABAJO RESPIRATORIO Y TOLERANCIA ORAL DISMINUIDA.",
        },
    ),
    "Asma / exacerbación broncoobstructiva": _caso(
        nombre="ASMA - EXACERBACIÓN LEVE A MODERADA",
        motivo="SIBILANCIAS Y TOS",
        enfermedad="PACIENTE CON ANTECEDENTE DE SIBILANCIAS RECURRENTES Y RESPUESTA PREVIA A BRONCODILATADOR, CONSULTA POR 24 HORAS DE TOS, SIBILANCIAS Y DISNEA LEVE. SIN FIEBRE, CIANOSIS, APNEAS, ALTERACIÓN DEL ESTADO DE CONCIENCIA, DOLOR TORÁCICO NI INTOLERANCIA A LA VÍA ORAL. REFIERE EXPOSICIÓN RECIENTE A CUADRO VIRAL; NIEGA EXPOSICIÓN A HUMO DE CIGARRILLO. DOCUMENTAR MEDICACIÓN PREVIA, TÉCNICA INHALATORIA, CONTROLADOR Y ESCALA DE SEVERIDAD.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HABLA EN FRASES, HIDRATADO, AFEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            nariz="PERMEABLE, SIN RINORREA ACTIVA.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL LEVE Y ESPIRACIÓN PROLONGADA.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR DISMINUIDO DE FORMA DIFUSA, CON SIBILANCIAS BILATERALES, SIN CIANOSIS.",
        ),
        diagnostico="J45 - ASMA",
        busqueda="asma",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN Y REVALORACIÓN OBJETIVA DE SEVERIDAD Y RESPUESTA.
{LINEA_SALBUTAMOL_NEBULIZADO}
- OXIMETRÍA SERIADA Y OXÍGENO SI REQUIERE.
- SE BRINDA EDUCACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE TÉCNICA INHALATORIA, SIGNOS DE ALARMA Y PLAN DE CONTROL.""",
        signos={"ta": "96/58", "fc": "124", "fr": "34", "sat": "94", "temp": "36.8", "peso": "18", "talla": "108", "pc": "", "pb": "16"},
        gpc="ASMA",
        fecha_nacimiento=date(2020, 3, 8),
        gpc_criterios={
            "SEVERIDAD / RESPUESTA": "SIBILANCIAS Y TIRAJE LEVE; REQUIERE ESCALA Y REVALORACIÓN POSTERIOR A BRONCODILATADOR.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 94% AL AIRE AMBIENTE.",
            "TÉCNICA O PLAN INHALATORIO": "SE INDICA INHALADOR CON ESPACIADOR Y EDUCACIÓN DE TÉCNICA.",
            "SIGNOS DE ALARMA / CONTROL": "SE REALIZA REVALORACIÓN DE RESPUESTA; EL EGRESO SE CONSIDERA SOLO SI HAY MEJORía. SE BRINDA INFORMACIÓN SOBRE SIGNOS DE ALARMA.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 34 RPM, TIRAJE SUBCOSTAL LEVE.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIBILANCIAS BILATERALES, SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 94% AL AIRE AMBIENTE; REVALORAR DESPUÉS DEL TRATAMIENTO.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN PARA OBJETIVAR RESPUESTA Y DEFINIR EGRESO.",
        },
    ),
    "Asma - hospitalización": _caso(
        nombre="ASMA - EXACERBACIÓN CON CRITERIOS DE HOSPITALIZACIÓN",
        motivo="DISNEA Y SIBILANCIAS",
        enfermedad="PACIENTE CON ASMA CONOCIDA, QUIEN PRESENTA 24 HORAS DE TOS, SIBILANCIAS Y AUMENTO PROGRESIVO DEL TRABAJO RESPIRATORIO. RECIBIÓ SALBUTAMOL DOMICILIARIO SIN MEJORÍA SOSTENIDA. PRESENTA DIFICULTAD PARA HABLAR EN FRASES COMPLETAS Y DISMINUCIÓN DE LA INGESTA. NIEGA FIEBRE, ASPIRACIÓN DE CUERPO EXTRAÑO, CIANOSIS CENTRAL, APNEAS, CONVULSIONES O ALTERACIÓN DEL ESTADO DE CONCIENCIA. DOCUMENTAR TRATAMIENTO CONTROLADOR, ADHERENCIA, TÉCNICA INHALATORIA Y DESENCADENANTES.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, ANSIOSO, TAQUIPNEICO, CON HABLA ENTRECORTADA, HIDRATACIÓN CONSERVADA Y AFEBRIL.",
            nariz="PERMEABLE, SIN SECRECIONES ABUNDANTES.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL E INTERCOSTAL MODERADO Y ESPIRACIÓN PROLONGADA.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR GLOBALMENTE DISMINUIDO, CON SIBILANCIAS BILATERALES; SIN CIANOSIS CENTRAL.",
        ),
        diagnostico="J45 - ASMA",
        busqueda="asma",
        conducta="HOSPITALIZACIÓN",
        plan="""- HOSPITALIZACIÓN PEDIÁTRICA, OXIMETRÍA SERIADA Y OXÍGENO SEGÚN RESPUESTA, ALTITUD Y PROTOCOLO INSTITUCIONAL.
{LINEA_SALBUTAMOL_NEBULIZADO}
{LINEA_METILPREDNISOLONA}
- REVALORACIÓN CLÍNICA Y ESCALA DE SEVERIDAD POSTERIOR A CADA CICLO DE BRONCODILATADOR.
- SE BRINDA EDUCACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE TÉCNICA INHALATORIA, DESENCADENANTES, SIGNOS DE ALARMA Y PLAN DE EGRESO AL LOGRAR ESTABILIZACIÓN.""",
        signos={"ta": "102/62", "fc": "142", "fr": "42", "sat": "89", "temp": "36.8", "peso": "25", "talla": "125", "pc": "", "pb": "18"},
        gpc="ASMA",
        fecha_nacimiento=date(2018, 10, 10),
        gpc_criterios={
            "SEVERIDAD / RESPUESTA": "TIRAJE MODERADO, HABLA ENTRECORTADA Y SIBILANCIAS DIFUSAS; REQUIERE TRATAMIENTO Y REVALORACIÓN SERIADA.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 89% AL AIRE AMBIENTE.",
            "TÉCNICA O PLAN INHALATORIO": "SE INDICA SALBUTAMOL CON ESPACIADOR/NEBULIZACIÓN SEGÚN RESPUESTA Y SE BRINDA EDUCACIÓN A PADRES O CUIDADOR RESPONSABLE.",
            "SIGNOS DE ALARMA / CONTROL": "VIGILANCIA INTRAHOSPITALARIA HASTA MEJORÍA DEL TRABAJO RESPIRATORIO, OXIGENACIÓN Y TOLERANCIA ORAL.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "SIN CONVULSIONES, LETARGIA NI INCAPACIDAD TOTAL PARA BEBER; INGESTA DISMINUIDA.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 42 RPM, TIRAJE SUBCOSTAL E INTERCOSTAL MODERADO.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIBILANCIAS BILATERALES, SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 89% AL AIRE AMBIENTE; REQUIERE OXÍGENO Y VIGILANCIA.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "HOSPITALIZACIÓN POR EXACERBACIÓN CON HIPOXEMIA, TRABAJO RESPIRATORIO Y RESPUESTA DOMICILIARIA INSUFICIENTE.",
        },
        justificacion="PRESENTA HIPOXEMIA, TIRAJE MODERADO, HABLA ENTRECORTADA Y SIBILANCIAS DIFUSAS DESPUÉS DE MANEJO DOMICILIARIO SIN MEJORÍA SOSTENIDA.",
    ),
    "Crup": _caso(
        nombre="CRUP - MANEJO Y OBSERVACIÓN",
        motivo="TOS PERRUNA Y ESTRIDOR",
        enfermedad="CUADRO DE 24 HORAS DE RINORREA, TOS PERRUNA Y DISFONÍA. ESTRIDOR SOLO AL LLANTO, AUSENTE EN REPOSO. TOLERA VÍA ORAL Y MANTIENE DIURESIS. NIEGA CIANOSIS, APNEAS, SIALORREA, DISFAGIA, POSICIÓN EN TRÍPODE, LETARGIA O INGESTA DE CUERPO EXTRAÑO. SIN EPISODIOS PREVIOS GRAVES DOCUMENTADOS.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADO, AFEBRIL, SIN SIGNOS GENERALES DE PELIGRO.",
            nariz="RINORREA HIALINA ESCASA.",
            orofaringe="MUCOSAS HÚMEDAS, SIN SIALORREA NI EXUDADO.",
            torax="SIMÉTRICO, NORMOEXPANSIBLE, SIN TIRAJES.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO. ESTRIDOR SOLO AL LLANTO, AUSENTE EN REPOSO; SIN SIBILANCIAS.",
        ),
        diagnostico="J05 - LARINGITIS OBSTRUCTIVA AGUDA [CRUP]",
        busqueda="crup",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN Y REVALORACIÓN DEL ESTRIDOR, TRABAJO RESPIRATORIO Y TOLERANCIA ORAL.
{LINEA_DEXAMETASONA_VO}
- ADRENALINA NEBULIZADA SOLO SI LA SEVERIDAD CLÍNICA LO INDICA, CON PERÍODO DE OBSERVACIÓN POSTERIOR.
- SE BRINDA EDUCACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA Y RECONSULTA.""",
        signos={"ta": "", "fc": "118", "fr": "28", "sat": "97", "temp": "37.8", "peso": "13", "talla": "92", "pc": "48", "pb": "15"},
        gpc="CRUP",
        fecha_nacimiento=date(2023, 8, 10),
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "ESTRIDOR SOLO AL LLANTO, SIN TIRAJES NI CIANOSIS.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 97% AL AIRE AMBIENTE.",
            "REVALORACIÓN": "REVALORAR POSTERIOR A LA INTERVENCIÓN Y ANTES DEL EGRESO.",
            "SIGNOS DE ALARMA / RECONSULTA": "SE INDICA RECONSULTAR POR ESTRIDOR EN REPOSO, TIRAJE, CIANOSIS, LETARGIA O INTOLERANCIA ORAL.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 28 RPM, SIN TIRAJES.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "ESTRIDOR AL LLANTO, AUSENTE EN REPOSO; SIN SIBILANCIAS.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 97% AL AIRE AMBIENTE; PACIENTE ALERTA E HIDRATADO.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN PARA REVALORACIÓN CLÍNICA Y DEFINIR EGRESO.",
        },
    ),
    "EDA / deshidratación": _caso(
        nombre="EDA CON ALGUNA DESHIDRATACIÓN - OBSERVACIÓN",
        motivo="VÓMITO Y DIARREA",
        enfermedad="CUADRO DE 24 HORAS DE DEPOSICIONES LÍQUIDAS, SIN SANGRE, ASOCIADAS A VÓMITOS. ACEPTA PEQUEÑOS SORBOS, PERO PRESENTA DIURESIS DISMINUIDA. NIEGA LETARGIA, CONVULSIONES, VÓMITO DE TODO LO INGERIDO, HEMATOQUEZIA, DISTENSIÓN ABDOMINAL PROGRESIVA O DOLOR ABDOMINAL INTENSO. SE INTERROGA NÚMERO DE DEPOSICIONES, CONTACTOS, ALIMENTOS DE RIESGO, ANTIBIÓTICOS RECIENTES Y ESQUEMA DE VACUNACIÓN.",
        examen=_examen_pediatrico_completo(
            "PACIENTE IRRITABLE, ALERTA, CON ALGUNOS SIGNOS DE DESHIDRATACIÓN, AFEBRIL.",
            nariz="PERMEABLE, SIN SECRECIONES.",
            orofaringe="MUCOSAS SECAS, SIN LESIONES.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN TIRAJES NI AGREGADOS.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, NO DOLOROSO, SIN MASAS NI SIGNOS DE IRRITACIÓN PERITONEAL.",
            piel="PIEL SIN LESIONES, PLIEGUE CUTÁNEO DE RETORNO LENTO, PERFUSIÓN CONSERVADA.",
        ),
        diagnostico="A09 - GASTROENTERITIS Y COLITIS DE ORIGEN NO ESPECIFICADO",
        busqueda="gastroenteritis",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y PLAN DE HIDRATACIÓN ORAL SEGÚN PESO Y CLASIFICACIÓN.
- CONTINUAR ALIMENTACIÓN SEGÚN TOLERANCIA, VIGILAR VÓMITO, DIURESIS Y SIGNOS VITALES.
- REVALORACIÓN CLÍNICA DEL ESTADO DE HIDRATACIÓN; DEFINIR EGRESO U HOSPITALIZACIÓN SEGÚN RESPUESTA.
- EDUCACIÓN DE SIGNOS DE ALARMA Y RECONSULTA.""",
        signos={"ta": "88/50", "fc": "128", "fr": "26", "sat": "98", "temp": "37.4", "peso": "12", "talla": "88", "pc": "48", "pb": "14.5"},
        gpc="EDA",
        aiepi="DIARREA",
        fecha_nacimiento=date(2024, 2, 20),
        gpc_criterios={
            "ESTADO DE HIDRATACIÓN": "ALGUNOS SIGNOS DE DESHIDRATACIÓN: MUCOSAS SECAS, OJOS LEVEMENTE HUNDIDOS Y PLIEGUE LENTO.",
            "TOLERANCIA ORAL / DIURESIS": "ACEPTA PEQUEÑOS SORBOS; DIURESIS DISMINUIDA EN VIGILANCIA.",
            "DECISIÓN DE SITIO DE MANEJO": "OBSERVACIÓN PARA PLAN DE HIDRATACIÓN Y REVALORACIÓN CLÍNICA.",
            "SIGNOS DE ALARMA / RECONSULTA": "SE INDICA RECONSULTAR POR LETARGIA, INTOLERANCIA TOTAL A VÍA ORAL, SANGRE EN HECES, DIURESIS AUSENTE O DETERIORO.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES: SIN LETARGIA, CONVULSIONES NI VÓMITO DE TODO LO INGERIDO.",
            "DURACIÓN, CARACTERÍSTICAS DE LAS DEPOSICIONES Y SANGRE EN HECES": "24 HORAS DE DIARREA LÍQUIDA, SIN SANGRE.",
            "ESTADO DE HIDRATACIÓN, TOLERANCIA ORAL Y DIURESIS": "MUCOSAS SECAS, OJOS LEVEMENTE HUNDIDOS, PLIEGUE LENTO; TOLERA PEQUEÑOS SORBOS Y DIURESIS DISMINUIDA.",
            "PLAN DE HIDRATACIÓN, ALIMENTACIÓN Y REVALORACIÓN": "PLAN DE HIDRATACIÓN ORAL Y REVALORACIÓN EN OBSERVACIÓN.",
            "SIGNOS DE ALARMA Y RECONSULTA": "SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA.",
        },
    ),
    "EDA con disentería - observación y coproscópico": _caso(
        nombre="EDA CON SANGRE EN HECES - OBSERVACIÓN Y COPROSCÓPICO",
        motivo="DIARREA CON SANGRE",
        enfermedad="CUADRO DE 2 DÍAS DE EVOLUCIÓN CON DEPOSICIONES LÍQUIDAS FRECUENTES, DOS EPISODIOS CON ESTRÍAS DE SANGRE Y DOLOR ABDOMINAL TIPO CÓLICO. ACEPTA PEQUEÑOS SORBOS, CON DIURESIS DISMINUIDA. NIEGA LETARGIA, CONVULSIONES, DISTENSIÓN ABDOMINAL PROGRESIVA, VÓMITO BILIOSO O VÓMITO DE TODO LO INGERIDO. SE DOCUMENTAN CONTACTOS, ALIMENTOS DE RIESGO, USO RECIENTE DE ANTIBIÓTICOS Y ESTADO VACUNAL.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, IRRITABLE, CON MUCOSAS LEVEMENTE SECAS, AFEBRIL Y PERFUSIÓN CONSERVADA.",
            orofaringe="MUCOSAS LEVEMENTE SECAS, SIN LESIONES.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, DOLOR LEVE DIFUSO A LA PALPACIÓN, SIN MASAS NI SIGNOS DE IRRITACIÓN PERITONEAL.",
        ),
        diagnostico="A09 - GASTROENTERITIS Y COLITIS DE ORIGEN NO ESPECIFICADO",
        busqueda="gastroenteritis",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y PLAN DE HIDRATACIÓN SEGÚN CLASIFICACIÓN CLÍNICA.
- COPROSCÓPICO Y ESTUDIOS COMPLEMENTARIOS SEGÚN HALLAZGOS, DADO EL REPORTE DE SANGRE EN HECES; DOCUMENTAR RESULTADOS Y SU IMPACTO EN LA CONDUCTA.
- CONTINUAR ALIMENTACIÓN SEGÚN TOLERANCIA, VIGILAR DIURESIS, NÚMERO Y CARACTERÍSTICAS DE LAS DEPOSICIONES.
- REVALORAR ESTADO DE HIDRATACIÓN Y EXAMEN ABDOMINAL PARA DEFINIR EGRESO, HOSPITALIZACIÓN O REMISIÓN.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA: LETARGIA, INTOLERANCIA TOTAL A VÍA ORAL, OLIGURIA/ANURIA, SANGRE ABUNDANTE, DOLOR INTENSO O DISTENSIÓN PROGRESIVA.""",
        signos={"ta": "90/54", "fc": "122", "fr": "25", "sat": "98", "temp": "37.5", "peso": "14", "talla": "96", "pc": "49", "pb": "15"},
        gpc="EDA", aiepi="DIARREA", fecha_nacimiento=date(2022, 5, 1),
        gpc_criterios={
            "ESTADO DE HIDRATACIÓN": "MUCOSAS LEVEMENTE SECAS, PERFUSIÓN CONSERVADA; REQUIERE REVALORACIÓN SERIADA.",
            "TOLERANCIA ORAL / DIURESIS": "ACEPTA PEQUEÑOS SORBOS; DIURESIS DISMINUIDA.",
            "DECISIÓN DE SITIO DE MANEJO": "OBSERVACIÓN POR DIARREA CON SANGRE, TOLERANCIA ORAL PARCIAL Y NECESIDAD DE REVALORACIÓN.",
            "SIGNOS DE ALARMA / RECONSULTA": "SIGNOS DE ALARMA DIGESTIVOS E HIDRATACIÓN INFORMADOS A PADRES O CUIDADOR RESPONSABLE.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES: SIN LETARGIA, CONVULSIONES NI VÓMITO DE TODO LO INGERIDO.",
            "DURACIÓN, CARACTERÍSTICAS DE LAS DEPOSICIONES Y SANGRE EN HECES": "2 DÍAS DE DIARREA; DOS EPISODIOS CON ESTRÍAS DE SANGRE.",
            "ESTADO DE HIDRATACIÓN, TOLERANCIA ORAL Y DIURESIS": "MUCOSAS LEVEMENTE SECAS, TOLERA PEQUEÑOS SORBOS, DIURESIS DISMINUIDA.",
            "PLAN DE HIDRATACIÓN, ALIMENTACIÓN Y REVALORACIÓN": "HIDRATACIÓN, ALIMENTACIÓN SEGÚN TOLERANCIA Y REVALORACIÓN EN OBSERVACIÓN.",
            "SIGNOS DE ALARMA Y RECONSULTA": "SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE DETERIORO, SANGRE ABUNDANTE, OLIGURIA Y DOLOR ABDOMINAL INTENSO.",
        },
        justificacion="EL REPORTE DE SANGRE EN HECES, LA TOLERANCIA ORAL PARCIAL Y LA DIURESIS DISMINUIDA JUSTIFICAN OBSERVACIÓN, HIDRATACIÓN Y ESTUDIO DE HECES SEGÚN EL CONTEXTO CLÍNICO.",
    ),
    "EDA grave - hospitalización": _caso(
        nombre="EDA CON DESHIDRATACIÓN GRAVE - HOSPITALIZACIÓN",
        motivo="DIARREA, VÓMITO E INTOLERANCIA ORAL",
        enfermedad="CUADRO DE 18 HORAS DE EVOLUCIÓN CON 12 DEPOSICIONES LÍQUIDAS Y 6 EPISODIOS DE VÓMITO. CUIDADOR REFIERE RECHAZO DE LA VÍA ORAL Y DISMINUCIÓN MARCADA DE LA DIURESIS. PRESENTA LETARGIA INTERMITENTE. NIEGA SANGRE EN HECES, VÓMITO BILIOSO, DISTENSIÓN ABDOMINAL PROGRESIVA O TRAUMA. SE DOCUMENTA NÚMERO DE DEPOSICIONES Y VÓMITOS, USO DE SRO, CONTACTOS, ALIMENTOS DE RIESGO Y TRATAMIENTOS PREVIOS.",
        examen=_examen_pediatrico_completo(
            "PACIENTE SOMNOLIENTO PERO DESPERTABLE, IRRITABLE AL EXAMEN, CON DESHIDRATACIÓN GRAVE, TAQUICARDIA Y PERFUSIÓN DISMINUIDA.",
            orofaringe="MUCOSAS MUY SECAS, SIN LESIONES.",
            cardiopulmonar="RUIDOS CARDÍACOS TAQUICÁRDICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN TIRAJES.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, SIN MASAS NI SIGNOS DE IRRITACIÓN PERITONEAL.",
            piel="PIEL PÁLIDA, PLIEGUE CUTÁNEO DE RETORNO MUY LENTO, EXTREMIDADES FRÍAS Y LLENADO CAPILAR PROLONGADO.",
        ),
        diagnostico="A09 - GASTROENTERITIS Y COLITIS DE ORIGEN NO ESPECIFICADO",
        busqueda="gastroenteritis",
        conducta="HOSPITALIZACIÓN",
        plan="""- HOSPITALIZACIÓN PEDIÁTRICA. ACCESO VENOSO, MONITORIZACIÓN CLÍNICA Y CONTROL DE SIGNOS VITALES.
- PLAN C DE REHIDRATACIÓN CON LACTATO DE RINGER: PARA 12 KG, 30 ML/KG (360 ML) EN 30 MINUTOS, SEGUIDO DE 70 ML/KG (840 ML) EN 2,5 HORAS POR SER MAYOR DE 12 MESES; REEVALUAR PERFUSIÓN, PULSO, ESTADO MENTAL Y ESTADO DE HIDRATACIÓN SEGÚN PROTOCOLO.
- OFRECER SRO TAN PRONTO COMO PUEDA BEBER Y REINTRODUCIR ALIMENTACIÓN ACORDE A LA EDAD SEGÚN TOLERANCIA.
- CONTROL ESTRICTO DE INGRESOS, EGRESOS, DIURESIS, GASTO FECAL Y VÓMITO; REVALORACIÓN CLÍNICA FRECUENTE.
- ELECTROLITOS, GLUCOSA Y OTROS PARACLÍNICOS DE EXTENSIÓN SEGÚN ESTADO CLÍNICO Y EVOLUCIÓN.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE LA INDICACIÓN DE HOSPITALIZACIÓN Y EL PLAN DE REHIDRATACIÓN.""",
        signos={"ta": "78/45", "fc": "156", "fr": "30", "sat": "98", "temp": "37.6", "peso": "12", "talla": "87", "pc": "47.5", "pb": "14"},
        gpc="EDA", aiepi="DIARREA", fecha_nacimiento=date(2024, 8, 15),
        gpc_criterios={
            "ESTADO DE HIDRATACIÓN": "DESHIDRATACIÓN GRAVE: SOMNOLENCIA INTERMITENTE, MUCOSAS MUY SECAS, PLIEGUE MUY LENTO, EXTREMIDADES FRÍAS Y LLENADO CAPILAR PROLONGADO.",
            "TOLERANCIA ORAL / DIURESIS": "RECHAZO DE VÍA ORAL Y DIURESIS MARCADAMENTE DISMINUIDA.",
            "DECISIÓN DE SITIO DE MANEJO": "HOSPITALIZACIÓN Y REHIDRATACIÓN ENDOVENOSA POR DESHIDRATACIÓN GRAVE E INTOLERANCIA ORAL.",
            "SIGNOS DE ALARMA / RECONSULTA": "VIGILANCIA INTRAHOSPITALARIA DE PERFUSIÓN, ESTADO MENTAL, DIURESIS Y RESPUESTA A REHIDRATACIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "LETARGIA INTERMITENTE Y RECHAZO DE VÍA ORAL.",
            "DURACIÓN, CARACTERÍSTICAS DE LAS DEPOSICIONES Y SANGRE EN HECES": "18 HORAS, 12 DEPOSICIONES LÍQUIDAS Y 6 VÓMITOS; SIN SANGRE EN HECES.",
            "ESTADO DE HIDRATACIÓN, TOLERANCIA ORAL Y DIURESIS": "DESHIDRATACIÓN GRAVE, NO TOLERA VÍA ORAL Y DIURESIS MARCADAMENTE DISMINUIDA.",
            "PLAN DE HIDRATACIÓN, ALIMENTACIÓN Y REVALORACIÓN": "PLAN C CON LACTATO DE RINGER, SRO AL TOLERAR Y REVALORACIÓN SERIADA.",
            "SIGNOS DE ALARMA Y RECONSULTA": "MANEJO INTRAHOSPITALARIO; CUIDADOR INFORMADO SOBRE EVOLUCIÓN Y SIGNOS DE DETERIORO.",
        },
        justificacion="PRESENTA DESHIDRATACIÓN GRAVE, RECHAZO DE LA VÍA ORAL, DIURESIS MARCADAMENTE DISMINUIDA Y SIGNOS DE HIPOPERFUSIÓN, POR LO QUE REQUIERE REHIDRATACIÓN ENDOVENOSA Y VIGILANCIA INTRAHOSPITALARIA.",
    ),
    "Bronquiolitis - hospitalización con oxígeno": _caso(
        nombre="BRONQUIOLITIS CON HIPOXEMIA - HOSPITALIZACIÓN",
        motivo="TOS, SIBILANCIAS Y DIFICULTAD RESPIRATORIA",
        enfermedad="LACTANTE DE 4 MESES CON 3 DÍAS DE CORIZA, RINORREA Y TOS, SEGUIDOS DE RESPIRACIÓN RUIDOSA Y DIFICULTAD RESPIRATORIA PROGRESIVA. PRIMER EPISODIO SIBILANTE. LACTANCIA DISMINUIDA, CON TOMAS CORTAS Y DIURESIS MENOR A LA HABITUAL. NIEGA APNEAS, CIANOSIS CENTRAL, CONVULSIONES Y VÓMITO DE TODO LO INGERIDO. SIN CARDIOPATÍA, DISPLASIA BRONCOPULMONAR, INMUNODEFICIENCIA NI PREMATURIDAD DE ALTO RIESGO DOCUMENTADAS.",
        examen=_examen_pediatrico_completo(
            "LACTANTE ALERTA, IRRITABLE, CON HIDRATACIÓN LEVEMENTE DISMINUIDA, TAQUIPNEA Y AUMENTO DEL TRABAJO RESPIRATORIO.",
            nariz="RINORREA HIALINA ABUNDANTE Y CONGESTIÓN NASAL.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL E INTERCOSTAL MODERADO Y ESPIRACIÓN PROLONGADA.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR BILATERALMENTE DISMINUIDO, CON SIBILANCIAS Y CREPITANTES FINOS DIFUSOS, SIN CIANOSIS CENTRAL.",
        ),
        diagnostico="J21 - BRONQUIOLITIS AGUDA",
        busqueda="bronquiolitis",
        conducta="HOSPITALIZACIÓN",
        plan="""- HOSPITALIZACIÓN PEDIÁTRICA, MONITORIZACIÓN RESPIRATORIA Y OXIMETRÍA SERIADA.
- OXÍGENO POR CÁNULA NASAL, TITULADO PARA MANTENER LA SATURACIÓN OBJETIVO DEFINIDA POR ALTITUD Y PROTOCOLO INSTITUCIONAL.
- HIGIENE NASAL Y ASPIRACIÓN DE SECRECIONES A NECESIDAD.
- LACTANCIA O LÍQUIDOS FRACCIONADOS SEGÚN TOLERANCIA; VIGILAR INGESTA, DIURESIS Y ESTADO DE HIDRATACIÓN.
{LINEA_ACETAMINOFEN}
- NO INDICAR ANTIBIÓTICOS, RADIOGRAFÍA DE TÓRAX, HEMOGRAMA, PCR O BRONCODILATADORES DE RUTINA SIN UNA JUSTIFICACIÓN CLÍNICA ESPECÍFICA.
- VALORAR ESCALA WOOD-DOWNES-FERRÉS MODIFICADA Y REEVALUAR RESPUESTA CLÍNICA PARA DEFINIR DESCENSO DE OXÍGENO Y EGRESO.""",
        signos={"ta": "", "fc": "154", "fr": "58", "sat": "88", "temp": "38.0", "peso": "6.5", "talla": "64", "pc": "42", "pb": "13.5"},
        gpc="BRONQUIOLITIS", aiepi="RESPIRATORIO", fecha_nacimiento=date(2026, 4, 20),
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "TAQUIPNEA, TIRAJE SUBCOSTAL E INTERCOSTAL MODERADO, SIBILANCIAS Y CREPITANTES DIFUSOS.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 88% AL AIRE AMBIENTE.",
            "HIDRATACIÓN / TOLERANCIA ORAL": "LACTANCIA DISMINUIDA, TOMAS CORTAS Y DIURESIS MENOR A LA HABITUAL.",
            "SIGNOS DE ALARMA / RECONSULTA": "HOSPITALIZACIÓN PARA OXIGENOTERAPIA, REVALORACIÓN RESPIRATORIA Y VIGILANCIA DE ALIMENTACIÓN/DIURESIS.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES: SIN APNEAS, CIANOSIS CENTRAL, CONVULSIONES NI VÓMITO DE TODO LO INGERIDO.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 58 RPM, TIRAJE SUBCOSTAL E INTERCOSTAL MODERADO.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "TIRAJE Y SIBILANCIAS DIFUSAS; SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 88% AL AIRE AMBIENTE; REQUIERE OXIGENOTERAPIA Y VIGILANCIA.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "BRONQUIOLITIS CON HIPOXEMIA Y DIFICULTAD RESPIRATORIA; SE DEFINE HOSPITALIZACIÓN.",
        },
        justificacion="LA HIPOXEMIA, LA TAQUIPNEA, EL TIRAJE MODERADO Y LA DISMINUCIÓN DE LA LACTANCIA JUSTIFICAN HOSPITALIZACIÓN PARA OXIGENOTERAPIA Y REVALORACIÓN SERIADA.",
    ),
    "IVU febril - hospitalización y urocultivo": _caso(
        nombre="INFECCIÓN URINARIA FEBRIL - HOSPITALIZACIÓN",
        motivo="FIEBRE Y DISURIA",
        enfermedad="PACIENTE DE 2 AÑOS CON FIEBRE CUANTIFICADA HASTA 39 °C, DISURIA, ORINA FÉTIDA Y DOLOR ABDOMINAL BAJO DE 24 HORAS DE EVOLUCIÓN. TOLERA VÍA ORAL, SIN VÓMITO PERSISTENTE. NIEGA DIARREA, TOS, DIFICULTAD RESPIRATORIA, CONVULSIONES, LETARGIA O DOLOR LUMBAR INTENSO. UROANÁLISIS CON LEUCOCITURIA, ESTERASA LEUCOCITARIA Y NITRITOS POSITIVOS. SE INDICA UROCULTIVO PREVIO AL ANTIBIÓTICO MEDIANTE MUESTRA DE CALIDAD SEGÚN CONTROL DE ESFÍNTERES.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADA, FEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, DOLOR LEVE SUPRAPÚBICO, SIN MASAS NI SIGNOS DE IRRITACIÓN PERITONEAL.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN TIRAJES NI AGREGADOS.",
        ),
        diagnostico="N39.0 - INFECCIÓN DE VÍAS URINARIAS, SITIO NO ESPECIFICADO",
        busqueda="infección urinaria",
        conducta="HOSPITALIZACIÓN",
        plan="""- HOSPITALIZACIÓN PEDIÁTRICA PARA VIGILANCIA CLÍNICA, RESULTADO DE UROCULTIVO Y AJUSTE TERAPÉUTICO.
- TOMAR UROCULTIVO ANTES DE INICIAR ANTIBIÓTICO, SI LA ESTABILIDAD CLÍNICA LO PERMITE; DOCUMENTAR TÉCNICA DE RECOLECCIÓN Y HORA DE TOMA.
{LINEA_CEFAZOLINA}
- HIDRATACIÓN Y DIETA ACORDE A LA EDAD SEGÚN TOLERANCIA.
{LINEA_ACETAMINOFEN}
- CONTROL DE SIGNOS VITALES, DIURESIS, CURVA TÉRMICA Y EVOLUCIÓN CLÍNICA; AVISAR CAMBIOS.
- SE INDICA REVISIÓN DE UROCULTIVO Y ANTIBIOGRAMA PARA CONFIRMAR DIAGNÓSTICO Y AJUSTAR ANTIBIÓTICO. DEFINIR IMÁGENES O ESTUDIOS ADICIONALES SEGÚN EVOLUCIÓN Y PROTOCOLO.""",
        signos={"ta": "92/58", "fc": "128", "fr": "26", "sat": "98", "temp": "39.0", "peso": "16", "talla": "100", "pc": "49.5", "pb": "16"},
        gpc="IVU", aiepi="FIEBRE_URINARIA", fecha_nacimiento=date(2024, 8, 4), sexo="Femenino",
        gpc_criterios={
            "FIEBRE, SÍNTOMAS URINARIOS Y ESTADO GENERAL": "FIEBRE 39 °C, DISURIA, ORINA FÉTIDA Y DOLOR SUPRAPÚBICO; PACIENTE ALERTA Y HEMODINÁMICAMENTE ESTABLE.",
            "UROANÁLISIS, TÉCNICA DE TOMA Y UROCULTIVO": "UROANÁLISIS CON LEUCOCITURIA, ESTERASA Y NITRITOS POSITIVOS; UROCULTIVO ANTES DE ANTIBIÓTICO CON TÉCNICA DOCUMENTADA.",
            "ANTIBIÓTICO Y SITIO DE MANEJO": "HOSPITALIZACIÓN PARA SEGUIMIENTO DE CULTIVO E INICIO EMPÍRICO DE CEFAZOLINA IV CALCULADA POR PESO.",
            "SEGUIMIENTO DE CULTIVO / SIGNOS DE ALARMA": "SE INDICA REVISAR UROCULTIVO/ANTIBIOGRAMA Y AJUSTAR TRATAMIENTO SEGÚN RESULTADO Y EVOLUCIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO Y ESTADO GENERAL": "AUSENTES: SIN LETARGIA, CONVULSIONES, DIFICULTAD RESPIRATORIA NI VÓMITO PERSISTENTE.",
            "FIEBRE, SÍNTOMAS URINARIOS Y FOCO CLÍNICO": "FIEBRE 39 °C, DISURIA, ORINA FÉTIDA Y DOLOR SUPRAPÚBICO; SIN OTRO FOCO CLÍNICO.",
            "UROANÁLISIS, TÉCNICA DE TOMA Y UROCULTIVO": "UROANÁLISIS PATOLÓGICO; UROCULTIVO PREVIO A ANTIBIÓTICO CON MUESTRA DE CALIDAD.",
            "CRITERIOS DE HOSPITALIZACIÓN, ANTIBIÓTICO Y REVALORACIÓN": "SE HOSPITALIZA PARA VIGILANCIA Y SEGUIMIENTO DEL CULTIVO; CEFAZOLINA IV EMPÍRICA SEGÚN PESO.",
            "SEGUIMIENTO DEL CULTIVO, SIGNOS DE ALARMA Y CONTROL": "AJUSTAR ANTIBIÓTICO SEGÚN ANTIBIOGRAMA Y EVOLUCIÓN; CUIDADOR INFORMADO.",
        },
        justificacion="LA FIEBRE ALTA CON UROANÁLISIS PATOLÓGICO Y LA NECESIDAD DE SEGUIMIENTO DEL UROCULTIVO Y TRATAMIENTO EMPÍRICO PARENTERAL JUSTIFICAN HOSPITALIZACIÓN SEGÚN EL PROTOCOLO INSTITUCIONAL.",
    ),
    "Síndrome broncoobstructivo - observación": _caso(
        nombre="SÍNDROME BRONCOOBSTRUCTIVO - OBSERVACIÓN Y RESPUESTA A BRONCODILATADOR",
        motivo="TOS, SIBILANCIAS Y DIFICULTAD RESPIRATORIA LEVE",
        enfermedad="PACIENTE DE 3 AÑOS CON 24 HORAS DE TOS, SIBILANCIAS AUDIBLES Y AUMENTO LEVE DEL TRABAJO RESPIRATORIO, POSTERIOR A RINORREA HIALINA. TIENE ANTECEDENTE DE DOS EPISODIOS PREVIOS DE SIBILANCIAS CON RESPUESTA A SALBUTAMOL. TOLERA VÍA ORAL Y MANTIENE DIURESIS. NIEGA FIEBRE, CIANOSIS, APNEAS, LETARGIA, CONVULSIONES, DOLOR TORÁCICO, ASPIRACIÓN DE CUERPO EXTRAÑO O VÓMITO PERSISTENTE.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADO, AFEBRIL, HEMODINÁMICAMENTE ESTABLE, CON DISNEA LEVE.",
            nariz="RINORREA HIALINA ESCASA, SIN ALETEO NASAL.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL LEVE Y ESPIRACIÓN PROLONGADA.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR DISMINUIDO LEVEMENTE DE FORMA DIFUSA, CON SIBILANCIAS ESPIRATORIAS BILATERALES, SIN ESTERTORES NI CIANOSIS.",
        ),
        diagnostico="R06.2 - SÍNDROME BRONCOOBSTRUCTIVO / SIBILANCIAS",
        busqueda="sibilancias",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y VALORACIÓN DE SEVERIDAD RESPIRATORIA CON ESCALA CLÍNICA INSTITUCIONAL.
{LINEA_SALBUTAMOL_NEBULIZADO}
- OXIMETRÍA SERIADA; OXÍGENO SOLO SI REQUIERE SEGÚN SATURACIÓN, ALTITUD Y PROTOCOLO.
- HIGIENE NASAL, HIDRATACIÓN Y VIGILANCIA DE TOLERANCIA ORAL.
- DEFINIR EGRESO U HOSPITALIZACIÓN SEGÚN RESPUESTA, TRABAJO RESPIRATORIO, SATURACIÓN Y CAPACIDAD DE CUIDADO EN CASA.
- SE BRINDA EDUCACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE TÉCNICA INHALATORIA, DESENCADENANTES Y SIGNOS DE ALARMA.""",
        signos={"ta": "92/56", "fc": "128", "fr": "38", "sat": "93", "temp": "36.8", "peso": "14", "talla": "95", "pc": "49", "pb": "15.5"},
        gpc="ASMA", aiepi="RESPIRATORIO", fecha_nacimiento=date(2023, 7, 10), sexo="Masculino",
        gpc_criterios={
            "SEVERIDAD / RESPUESTA": "SIBILANCIAS BILATERALES, ESPIRACIÓN PROLONGADA Y TIRAJE SUBCOSTAL LEVE; PENDIENTE DOCUMENTAR RESPUESTA OBJETIVA POSTERIOR A SALBUTAMOL.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 93% AL AIRE AMBIENTE.",
            "TÉCNICA O PLAN INHALATORIO": "SALBUTAMOL CON ESPACIADOR Y EDUCACIÓN DE TÉCNICA INHALATORIA.",
            "SIGNOS DE ALARMA / CONTROL": "OBSERVACIÓN PARA REVALORACIÓN; SE BRINDA INFORMACIÓN SOBRE RECONSULTA POR TIRAJE, CIANOSIS, SOMNOLENCIA O INTOLERANCIA ORAL.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 38 RPM, TIRAJE SUBCOSTAL LEVE.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIBILANCIAS ESPIRATORIAS BILATERALES; SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 93% AL AIRE AMBIENTE; REVALORAR TRAS BRONCODILATADOR.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN PARA OBJETIVAR RESPUESTA Y DEFINIR SITIO DE MANEJO.",
        },
        justificacion="EL TRABAJO RESPIRATORIO LEVE, LA SATURACIÓN LIMÍTROFE Y LA NECESIDAD DE OBJETIVAR RESPUESTA A BRONCODILATADOR JUSTIFICAN OBSERVACIÓN PEDIÁTRICA.",
    ),
    "Síndrome febril / fiebre sin foco - observación": _caso(
        nombre="SÍNDROME FEBRIL SIN FOCO - OBSERVACIÓN Y BÚSQUEDA DIRIGIDA",
        motivo="FIEBRE SIN FOCO CLARO",
        enfermedad="LACTANTE DE 15 MESES CON FIEBRE CUANTIFICADA HASTA 39.4 °C DE 24 HORAS DE EVOLUCIÓN, IRRITABILIDAD DURANTE LOS PICOS FEBRILES Y DISMINUCIÓN LEVE DEL APETITO. TOLERA LÍQUIDOS Y PRESENTA DIURESIS. NIEGA TOS, RINORREA, DIFICULTAD RESPIRATORIA, VÓMITO, DIARREA, DISURIA, EXANTEMA, PETEQUIAS, RIGIDEZ DE CUELLO, CONVULSIONES, SOMNOLENCIA ANORMAL O CONTACTO CON ENFERMEDAD GRAVE. SIN FOCO CLÍNICO EVIDENTE EN LA VALORACIÓN INICIAL.",
        examen=_examen_pediatrico_completo(
            "LACTANTE ALERTA, IRRITABLE SOLO DURANTE LA MANIPULACIÓN, HIDRATADO, FEBRIL, BIEN PERFUNDIDO.",
            orofaringe="MUCOSAS HÚMEDAS, SIN ERITEMA IMPORTANTE, EXUDADO NI ÚLCERAS.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN TIRAJES NI AGREGADOS.",
            piel="ROSADA, BIEN PERFUNDIDA, SIN EXANTEMA, PETEQUIAS NI EQUIMOSIS.",
        ),
        diagnostico="R50.9 - SÍNDROME FEBRIL / FIEBRE SIN FOCO",
        busqueda="fiebre no especificada",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA, CURVA TÉRMICA Y REVALORACIÓN DEL ESTADO GENERAL Y APARICIÓN DE FOCO CLÍNICO.
- HIDRATACIÓN ORAL FRACCIONADA Y ALIMENTACIÓN SEGÚN TOLERANCIA.
{LINEA_ACETAMINOFEN}
- CONSIDERAR UROANÁLISIS Y UROCULTIVO CON TÉCNICA ADECUADA SI PERSISTE FIEBRE SIN FOCO O SEGÚN EDAD, SEXO Y PROTOCOLO INSTITUCIONAL.
- PARACLÍNICOS ADICIONALES SOLO SEGÚN HALLAZGOS CLÍNICOS, EVOLUCIÓN Y PROTOCOLO.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA: DETERIORO DEL ESTADO GENERAL, CONVULSIONES, PETEQUIAS, RIGIDEZ DE CUELLO, DIFICULTAD RESPIRATORIA, INTOLERANCIA ORAL O DIURESIS DISMINUIDA.""",
        signos={"ta": "90/54", "fc": "142", "fr": "30", "sat": "98", "temp": "39.1", "peso": "10.5", "talla": "80", "pc": "47", "pb": "14.5"},
        gpc="FIEBRE", aiepi="FIEBRE", fecha_nacimiento=date(2025, 5, 15), sexo="Femenino",
        gpc_criterios={
            "ESTADO GENERAL, TIEMPO DE EVOLUCIÓN Y TEMPERATURA": "24 HORAS DE FIEBRE HASTA 39.4 °C; ALERTA, HIDRATADA Y BIEN PERFUNDIDA.",
            "BÚSQUEDA DE FOCO Y SIGNOS DE ALARMA": "SIN FOCO CLÍNICO, PETEQUIAS, RIGIDEZ DE CUELLO, CONVULSIONES NI DIFICULTAD RESPIRATORIA.",
            "PARACLÍNICOS Y SITIO DE MANEJO": "OBSERVACIÓN Y BÚSQUEDA DIRIGIDA DE FOCO; CONSIDERAR ORINA SEGÚN EVOLUCIÓN Y PROTOCOLO.",
            "SIGNOS DE ALARMA / CONTROL": "REVALORACIÓN DURANTE OBSERVACIÓN Y CONSEJERÍA DE RECONSULTA.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO Y ESTADO GENERAL": "AUSENTES; ALERTA, HIDRATADA Y BIEN PERFUNDIDA.",
            "TIEMPO DE EVOLUCIÓN, TEMPERATURA Y FOCO CLÍNICO": "24 HORAS, TEMPERATURA MÁXIMA 39.4 °C, SIN FOCO CLÍNICO EVIDENTE.",
            "EXANTEMA, RIGIDEZ DE CUELLO, PETEQUIAS U OTROS SIGNOS DE ALARMA SI APLICAN": "AUSENTES.",
            "EXÁMENES COMPLEMENTARIOS O JUSTIFICACIÓN DE NO SOLICITARLOS": "UROANÁLISIS/UROCULTIVO SEGÚN EVOLUCIÓN Y FACTORES DE RIESGO; SIN OTROS PARACLÍNICOS DE RUTINA AL INGRESO.",
            "CONDUCTA, SIGNOS DE ALARMA Y CONTROL": "OBSERVACIÓN, CURVA TÉRMICA, REVALORACIÓN Y SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE.",
        },
        justificacion="LA FIEBRE ALTA SIN FOCO IDENTIFICADO AMERITA OBSERVACIÓN Y BÚSQUEDA DIRIGIDA DE ETIOLOGÍA, MANTENIENDO VIGILANCIA DE SIGNOS DE ALARMA Y EVOLUCIÓN CLÍNICA.",
    ),
    "Riesgo de desnutrición aguda - ambulatorio": _caso(
        nombre="RIESGO DE DESNUTRICIÓN AGUDA - MANEJO AMBULATORIO Y SEGUIMIENTO",
        motivo="BAJO AUMENTO DE PESO",
        enfermedad="PACIENTE DE 2 AÑOS ENVIADO POR DESCENSO PONDERAL PERCIBIDO DURANTE LOS ÚLTIMOS 2 MESES. CUIDADOR REFIERE APETITO VARIABLE, SIN VÓMITO, DIARREA, FIEBRE, TOS CRÓNICA, DIFICULTAD RESPIRATORIA, EDEMAS, POLIURIA, SANGRE EN HECES NI DISMINUCIÓN DE LA ACTIVIDAD. TOLERA VÍA ORAL, PRESENTA DIURESIS Y DEPOSICIONES HABITUALES. NO HAY DATOS DE INSEGURIDAD ALIMENTARIA GRAVE DOCUMENTADOS; SE REQUIERE PROFUNDIZAR ENCUESTA NUTRICIONAL.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, ACTIVO, HIDRATADO, AFEBRIL, SIN SIGNOS GENERALES DE PELIGRO.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, NO DOLOROSO, SIN HEPATOESPLENOMEGALIA NI SIGNOS DE IRRITACIÓN PERITONEAL.",
            piel="ROSADA, BIEN PERFUNDIDA, SIN EDEMA BILATERAL, LESIONES NI CAMBIOS CUTÁNEOS SUGESTIVOS DE DEFICIENCIA NUTRICIONAL.",
        ),
        diagnostico="E44 - RIESGO DE DESNUTRICIÓN AGUDA",
        busqueda="desnutrición proteico calórica",
        conducta="EGRESO",
        plan="""- CONFIRMAR CLASIFICACIÓN ANTROPOMÉTRICA CON ESTÁNDARES OMS, PESO/TALLA, IMC/EDAD, TALLA/EDAD, PB Y BÚSQUEDA DE EDEMA BILATERAL.
- CONSEJERÍA ALIMENTARIA INDIVIDUALIZADA, REVISIÓN DE FRECUENCIA, CONSISTENCIA, DENSIDAD ENERGÉTICA Y DIVERSIDAD DE LA DIETA.
- REMISIÓN O SEGUIMIENTO POR NUTRICIÓN Y PEDIATRÍA SEGÚN RUTA INTEGRAL Y PROTOCOLO INSTITUCIONAL.
- CONTROL ANTROPOMÉTRICO CERCANO; FECHA SEGÚN CLASIFICACIÓN, EVOLUCIÓN Y DISPONIBILIDAD INSTITUCIONAL.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA: RECHAZO ALIMENTARIO, VÓMITO PERSISTENTE, DIARREA, FIEBRE, EDEMAS, LETARGIA O PÉRDIDA PONDERAL RÁPIDA.""",
        signos={"ta": "88/52", "fc": "102", "fr": "24", "sat": "98", "temp": "36.7", "peso": "10", "talla": "84", "pc": "48", "pb": "13.2"},
        gpc="DESNUTRICION", aiepi="INTEGRAL", fecha_nacimiento=date(2024, 8, 1), sexo="Masculino",
        gpc_criterios={
            "ANTROPOMETRÍA, PB Y EDEMA BILATERAL": "PESO, TALLA Y PB REGISTRADOS; SIN EDEMA BILATERAL. CORROBORAR Z-SCORES OMS EN LA HISTORIA.",
            "APETITO, INGESTA, HIDRATACIÓN Y SIGNOS DE PELIGRO": "APETITO VARIABLE, TOLERA VÍA ORAL, HIDRATADO, SIN SIGNOS GENERALES DE PELIGRO.",
            "CLASIFICACIÓN Y SITIO DE MANEJO": "RIESGO NUTRICIONAL SIN COMPLICACIONES CLÍNICAS; MANEJO AMBULATORIO CON CONTROL ESTRECHO.",
            "PLAN NUTRICIONAL / CONTROL": "CONSEJERÍA ALIMENTARIA, SEGUIMIENTO ANTROPOMÉTRICO Y REMISIÓN A NUTRICIÓN SEGÚN RUTA.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO Y ESTADO GENERAL": "AUSENTES; PACIENTE ALERTA, ACTIVO E HIDRATADO.",
            "ALIMENTACIÓN, HIDRATACIÓN Y DIURESIS": "APETITO VARIABLE, TOLERA VÍA ORAL, DIURESIS Y DEPOSICIONES CONSERVADAS.",
            "CRECIMIENTO, DESARROLLO Y ESTADO NUTRICIONAL CUANDO APLIQUE": "ANTROPOMETRÍA Y PB REGISTRADOS; RIESGO NUTRICIONAL A CORROBORAR CON OMS.",
            "INMUNIZACIÓN, CONSEJERÍA Y MEDIDAS DE PREVENCIÓN": "CONSEJERÍA ALIMENTARIA Y VERIFICACIÓN DE VACUNACIÓN/ENTORNO FAMILIAR.",
            "SIGNOS DE ALARMA, CONTROL Y RECONSULTA": "CONTROL ANTROPOMÉTRICO CERCANO Y RECONSULTA POR SIGNOS DE DETERIORO.",
        },
        justificacion="NO HAY EDEMA, RECHAZO ALIMENTARIO, DESHIDRATACIÓN NI SIGNOS GENERALES DE PELIGRO; SE PRIORIZA MANEJO AMBULATORIO CON SEGUIMIENTO ANTROPOMÉTRICO Y NUTRICIONAL ESTRECHO.",
    ),
    "TCE leve - observación": _caso(
        nombre="TRAUMA CRANEOENCEFÁLICO LEVE - OBSERVACIÓN NEUROLÓGICA",
        motivo="GOLPE EN LA CABEZA",
        enfermedad="PACIENTE DE 5 AÑOS QUE SUFRE CAÍDA DESDE SU PROPIA ALTURA HACE 2 HORAS, CON GOLPE FRONTAL. LLORÓ INMEDIATAMENTE, SIN PÉRDIDA DE CONOCIMIENTO, AMNESIA, CONVULSIONES, SOMNOLENCIA, CAMBIO DE CONDUCTA, DÉFICIT MOTOR, OTORRAGIA O RINORREA. PRESENTÓ DOS EPISODIOS DE VÓMITO POSTERIORES AL EVENTO. TOLERA PEQUEÑOS LÍQUIDOS Y NO TIENE ANTECEDENTES DE TRASTORNO DE COAGULACIÓN NI USO DE ANTICOAGULANTES.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, ORIENTADO PARA LA EDAD, HIDRATADO, AFEBRIL, GLASGOW 15/15.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN AGREGADOS.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, NO DOLOROSO, SIN SIGNOS DE IRRITACIÓN PERITONEAL.",
            piel="HEMATOMA FRONTAL PEQUEÑO, SIN HERIDA ABIERTA, SIN EQUIMOSIS PERIORBITARIA, RETROAURICULAR NI OTROS SIGNOS DE FRACTURA BASILAR.",
        ),
        diagnostico="S06.0 - TRAUMA CRANEOENCEFÁLICO LEVE / CONMOCIÓN CEREBRAL",
        busqueda="conmoción cerebral",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN NEUROLÓGICA SERIADA: GLASGOW, ESTADO MENTAL, SIGNOS VITALES, VÓMITO, CEFALEA Y HALLAZGOS NEUROLÓGICOS.
{LINEA_ACETAMINOFEN}
- OFRECER LÍQUIDOS SEGÚN TOLERANCIA Y VIGILAR VÓMITO.
- DEFINIR NECESIDAD DE NEUROIMAGEN, INTERCONSULTA O REMISIÓN SEGÚN REGLA CLÍNICA INSTITUCIONAL, DETERIORO NEUROLÓGICO O FACTORES DE RIESGO.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA: SOMNOLENCIA PROGRESIVA, CONVULSIONES, VÓMITO REPETIDO, CEFALEA INTENSA, CONFUSIÓN, DÉFICIT, SALIDA DE LÍQUIDO POR NARIZ/OÍDO O DETERIORO CLÍNICO.""",
        signos={"ta": "96/60", "fc": "102", "fr": "22", "sat": "98", "temp": "36.8", "peso": "19", "talla": "110", "pc": "", "pb": "16.5"},
        gpc="", aiepi="INTEGRAL", fecha_nacimiento=date(2021, 8, 3), sexo="Masculino",
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO Y ESTADO GENERAL": "ALERTA, GLASGOW 15/15, SIN CONVULSIONES NI SOMNOLENCIA.",
            "ALIMENTACIÓN, HIDRATACIÓN Y DIURESIS": "TOLERA PEQUEÑOS LÍQUIDOS; DOS VÓMITOS POSTRAUMA EN VIGILANCIA.",
            "CRECIMIENTO, DESARROLLO Y ESTADO NUTRICIONAL CUANDO APLIQUE": "DESARROLLO ACORDE A LA EDAD SEGÚN CUIDADOR; ANTROPOMETRÍA REGISTRADA.",
            "INMUNIZACIÓN, CONSEJERÍA Y MEDIDAS DE PREVENCIÓN": "CONSEJERÍA DE PREVENCIÓN DE CAÍDAS Y VIGILANCIA DOMICILIARIA.",
            "SIGNOS DE ALARMA, CONTROL Y RECONSULTA": "OBSERVACIÓN NEUROLÓGICA Y SIGNOS DE ALARMA INFORMADOS A PADRES O CUIDADOR RESPONSABLE.",
        },
        justificacion="EL VÓMITO POSTRAUMA AMERITA OBSERVACIÓN NEUROLÓGICA SERIADA, AUNQUE EL EXAMEN INICIAL Y EL GLASGOW SEAN NORMALES.",
    ),
    "Síndrome emético / vómito - observación": _caso(
        nombre="SÍNDROME EMÉTICO - OBSERVACIÓN Y REHIDRATACIÓN ORAL",
        motivo="VÓMITO E INTOLERANCIA ORAL PARCIAL",
        enfermedad="PACIENTE DE 3 AÑOS CON 12 HORAS DE VÓMITO DE CONTENIDO ALIMENTARIO EN SEIS OPORTUNIDADES, ASOCIADO A DOLOR ABDOMINAL DIFUSO LEVE. ACEPTA PEQUEÑOS SORBOS, CON DIURESIS DISMINUIDA PERO PRESENTE. NIEGA VÓMITO BILIOSO, HEMATEMESIS, DIARREA, FIEBRE, CEFALEA, TRAUMA, INGESTA TÓXICA, DISTENSIÓN ABDOMINAL, SANGRE EN HECES, DISURIA O SOMNOLENCIA.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, CON MUCOSAS LEVEMENTE SECAS, AFEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, DOLOR DIFUSO LEVE A LA PALPACIÓN, SIN DEFENSA, REBOTE, MASAS NI SIGNOS DE IRRITACIÓN PERITONEAL.",
        ),
        diagnostico="R11 - SÍNDROME EMÉTICO / VÓMITO",
        busqueda="vómito",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN, REVALORACIÓN ABDOMINAL SERIADA Y VIGILANCIA DE ESTADO DE HIDRATACIÓN.
- REHIDRATACIÓN ORAL FRACCIONADA CON SRO; CUANTIFICAR TOLERANCIA, VÓMITOS Y DIURESIS.
{LINEA_ONDANSETRON}
- DEFINIR PARACLÍNICOS, IMÁGENES, VALORACIÓN QUIRÚRGICA O REMISIÓN SI APARECEN VÓMITO BILIOSO, DOLOR LOCALIZADO/PROGRESIVO, DISTENSIÓN, SIGNOS PERITONEALES O DETERIORO.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA Y PLAN DE REVALORACIÓN.""",
        signos={"ta": "90/55", "fc": "120", "fr": "26", "sat": "98", "temp": "36.9", "peso": "13", "talla": "92", "pc": "48.5", "pb": "15"},
        gpc="", aiepi="INTEGRAL", fecha_nacimiento=date(2023, 4, 2), sexo="Femenino",
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO Y ESTADO GENERAL": "ALERTA, SIN LETARGIA, CONVULSIONES NI VÓMITO BILIOSO/HEMÁTICO.",
            "ALIMENTACIÓN, HIDRATACIÓN Y DIURESIS": "ACEPTA PEQUEÑOS SORBOS; MUCOSAS LEVEMENTE SECAS Y DIURESIS DISMINUIDA PERO PRESENTE.",
            "CRECIMIENTO, DESARROLLO Y ESTADO NUTRICIONAL CUANDO APLIQUE": "ANTROPOMETRÍA REGISTRADA; SIN DATOS DE DETERIORO NUTRICIONAL AGUDO.",
            "INMUNIZACIÓN, CONSEJERÍA Y MEDIDAS DE PREVENCIÓN": "CONSEJERÍA SOBRE SRO, HIGIENE Y EVITAR AUTOMEDICACIÓN.",
            "SIGNOS DE ALARMA, CONTROL Y RECONSULTA": "SE REALIZA REVALORACIÓN EN OBSERVACIÓN Y SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA ABDOMINAL.",
        },
        justificacion="LA FRECUENCIA DE VÓMITO Y LA TOLERANCIA ORAL PARCIAL REQUIEREN OBSERVACIÓN Y REHIDRATACIÓN ORAL SUPERVISADA, SIN DATOS INICIALES DE ABDOMEN AGUDO.",
    ),
    "Dolor abdominal - observación": _caso(
        nombre="DOLOR ABDOMINAL EN ESTUDIO - OBSERVACIÓN",
        motivo="DOLOR ABDOMINAL LOCALIZADO",
        enfermedad="PACIENTE DE 7 AÑOS CON 18 HORAS DE DOLOR ABDOMINAL INICIALMENTE PERIUMBILICAL, ACTUALMENTE PREDOMINANTE EN FOSA ILÍACA DERECHA, ASOCIADO A ANOREXIA Y NÁUSEA, SIN VÓMITO. NIEGA FIEBRE, DIARREA, DISURIA, HEMATURIA, TRAUMA, SANGRE EN HECES O DOLOR TESTICULAR. DIURESIS PRESENTE. NO HA RECIBIDO ANTIBIÓTICOS NI ANALGÉSICOS PREVIOS.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADO, AFEBRIL, HEMODINÁMICAMENTE ESTABLE, CON FACIES ÁLGICA LEVE.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, DOLOR A LA PALPACIÓN EN FOSA ILÍACA DERECHA, SIN DEFENSA INVOLUNTARIA, REBOTE NI MASAS; EXAMEN ABDOMINAL SERIADO INDICADO.",
        ),
        diagnostico="R10 - DOLOR ABDOMINAL EN ESTUDIO",
        busqueda="dolor abdominal",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA CON EXAMEN ABDOMINAL SERIADO, CONTROL DE SIGNOS VITALES, DOLOR, VÓMITO Y TOLERANCIA ORAL.
- DIETA SEGÚN EVOLUCIÓN Y PROTOCOLO; DEFINIR AYUNO SI AUMENTA LA SOSPECHA QUIRÚRGICA.
{LINEA_ACETAMINOFEN}
- HEMOGRAMA, UROANÁLISIS, ECOGRAFÍA ABDOMINAL Y VALORACIÓN POR CIRUGÍA PEDIÁTRICA SEGÚN HALLAZGOS, EVOLUCIÓN Y PROTOCOLO INSTITUCIONAL.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA: DOLOR INTENSO O PROGRESIVO, VÓMITO BILIOSO, DISTENSIÓN, FIEBRE, RIGIDEZ ABDOMINAL, SANGRE EN HECES O DETERIORO GENERAL.""",
        signos={"ta": "98/62", "fc": "105", "fr": "22", "sat": "99", "temp": "37.1", "peso": "24", "talla": "121", "pc": "", "pb": "17"},
        gpc="", aiepi="INTEGRAL", fecha_nacimiento=date(2019, 7, 18), sexo="Masculino",
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO Y ESTADO GENERAL": "ALERTA, HIDRATADO, SIN LETARGIA NI CONVULSIONES.",
            "ALIMENTACIÓN, HIDRATACIÓN Y DIURESIS": "ANOREXIA LEVE, DIURESIS PRESENTE, SIN VÓMITO.",
            "CRECIMIENTO, DESARROLLO Y ESTADO NUTRICIONAL CUANDO APLIQUE": "ANTROPOMETRÍA REGISTRADA; DESARROLLO ACORDE A LA EDAD SEGÚN CUIDADOR.",
            "INMUNIZACIÓN, CONSEJERÍA Y MEDIDAS DE PREVENCIÓN": "CUIDADOR INFORMADO SOBRE VIGILANCIA Y NO AUTOMEDICACIÓN.",
            "SIGNOS DE ALARMA, CONTROL Y RECONSULTA": "OBSERVACIÓN Y EXAMEN ABDOMINAL SERIADO POR DOLOR LOCALIZADO.",
        },
        justificacion="LA MIGRACIÓN Y LOCALIZACIÓN DEL DOLOR EN FOSA ILÍACA DERECHA AMERITAN OBSERVACIÓN, EXAMEN SERIADO Y ESTUDIOS DIRIGIDOS PARA DESCARTAR PATOLOGÍA QUIRÚRGICA.",
    ),
    "Estreñimiento / constipación - ambulatorio": _caso(
        nombre="ESTREÑIMIENTO FUNCIONAL - MANEJO AMBULATORIO",
        motivo="EVACUACIONES ESCASAS Y DOLOROSAS",
        enfermedad="PACIENTE DE 4 AÑOS CON DOS MESES DE DEPOSICIONES CADA 3 A 4 DÍAS, CONSISTENCIA DURA TIPO BRISTOL 1-2, DOLOR AL DEFECAR Y CONDUCTA RETENTIVA. REFIERE EPISODIOS OCASIONALES DE HECES VOLUMINOSAS, SIN SANGRE. NIEGA VÓMITO BILIOSO, DISTENSIÓN PERSISTENTE, FIEBRE, PÉRDIDA PONDERAL, INCONTINENCIA URINARIA, DEBILIDAD DE MIEMBROS INFERIORES, RETARDO EN LA ELIMINACIÓN DE MECONIO O ANTECEDENTES NEUROLÓGICOS. DIETA BAJA EN FIBRA Y HÁBITO INTESTINAL IRREGULAR.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADO, AFEBRIL, EN BUEN ESTADO GENERAL.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, MASA FECAL PALPABLE EN HIPOGASTRIO IZQUIERDO, SIN DOLOR IMPORTANTE, DEFENSA NI SIGNOS DE IRRITACIÓN PERITONEAL.",
            piel="ROSADA, BIEN PERFUNDIDA, SIN FISURA ANAL EVIDENTE EN LA INSPECCIÓN EXTERNA; EXAMEN ANORRECTAL COMPLETO SEGÚN INDICACIÓN Y CONSENTIMIENTO.",
        ),
        diagnostico="K59.0 - ESTREÑIMIENTO / CONSTIPACIÓN FUNCIONAL",
        busqueda="estreñimiento",
        conducta="EGRESO",
        plan="""- SE BRINDA EDUCACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE ESTREÑIMIENTO FUNCIONAL, HÁBITO INTESTINAL REGULAR POSTPRANDIAL, POSICIÓN ADECUADA Y REFUERZO POSITIVO.
- AUMENTAR AGUA, FIBRA, FRUTAS Y VERDURAS SEGÚN EDAD Y TOLERANCIA; EVITAR MEDIDAS PUNITIVAS.
- DEFINIR DESIMPACTACIÓN Y/O TRATAMIENTO DE MANTENIMIENTO CON LAXANTE OSMÓTICO SEGÚN PESO, SEVERIDAD Y PROTOCOLO INSTITUCIONAL.
- CONTROL POR PEDIATRÍA PARA VALORAR RESPUESTA, ADHERENCIA, CRECIMIENTO Y AJUSTE DEL PLAN.
- RECONSULTAR POR VÓMITO BILIOSO, DISTENSIÓN PROGRESIVA, SANGRADO PERSISTENTE, FIEBRE, PÉRDIDA DE PESO, DOLOR INTENSO O AUSENCIA DE RESPUESTA.""",
        signos={"ta": "94/58", "fc": "96", "fr": "22", "sat": "98", "temp": "36.6", "peso": "17", "talla": "104", "pc": "", "pb": "16"},
        gpc="", aiepi="INTEGRAL", fecha_nacimiento=date(2022, 3, 9), sexo="Femenino",
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO Y ESTADO GENERAL": "AUSENTES; BUEN ESTADO GENERAL.",
            "ALIMENTACIÓN, HIDRATACIÓN Y DIURESIS": "HIDRATACIÓN Y DIURESIS CONSERVADAS; DIETA BAJA EN FIBRA IDENTIFICADA.",
            "CRECIMIENTO, DESARROLLO Y ESTADO NUTRICIONAL CUANDO APLIQUE": "ANTROPOMETRÍA REGISTRADA; VIGILAR CRECIMIENTO EN CONTROLES.",
            "INMUNIZACIÓN, CONSEJERÍA Y MEDIDAS DE PREVENCIÓN": "CONSEJERÍA SOBRE HÁBITO INTESTINAL, DIETA Y EVITAR MEDIDAS PUNITIVAS.",
            "SIGNOS DE ALARMA, CONTROL Y RECONSULTA": "SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA Y CONTROL PEDIÁTRICO.",
        },
        justificacion="LOS DATOS CLÍNICOS SON COMPATIBLES CON ESTREÑIMIENTO FUNCIONAL SIN BANDERAS ROJAS, POR LO QUE SE INDICA MANEJO AMBULATORIO, INTERVENCIÓN CONDUCTUAL Y SEGUIMIENTO.",
    ),
    "Otitis media aguda - ambulatorio": _caso(
        nombre="OTITIS MEDIA AGUDA - MANEJO AMBULATORIO",
        motivo="OTALGIA Y FIEBRE",
        enfermedad="PACIENTE DE 2 AÑOS CON 48 HORAS DE OTALGIA DERECHA, IRRITABILIDAD Y FIEBRE HASTA 38.6 °C, PRECEDIDAS POR RINORREA. TOLERA VÍA ORAL Y PRESENTA DIURESIS. NIEGA OTORREA, EDEMA O DOLOR RETROAURICULAR, VÓMITO PERSISTENTE, DIFICULTAD RESPIRATORIA, LETARGIA, CONVULSIONES O SIGNOS NEUROLÓGICOS. SIN TRATAMIENTO ANTIBIÓTICO PARA EL CUADRO ACTUAL.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADO, FEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            nariz="RINORREA HIALINA ESCASA, SIN ALETEO NASAL.",
            orofaringe="MUCOSAS HÚMEDAS, SIN EXUDADO.",
            piel="ROSADA, BIEN PERFUNDIDA, SIN EDEMA, ERITEMA NI DOLOR RETROAURICULAR.",
        ).replace("OÍDOS: SIN ALTERACIONES EVIDENTES.", "OÍDOS: OTOSCOPIA DERECHA CON MEMBRANA TIMPÁNICA ERITEMATOSA, ABOMBADA Y CON MOVILIDAD DISMINUIDA; OÍDO IZQUIERDO SIN ALTERACIONES EVIDENTES."),
        diagnostico="H66.0 - OTITIS MEDIA AGUDA",
        busqueda="otitis media aguda",
        conducta="EGRESO",
        plan="""{LINEA_ACETAMINOFEN}
{LINEA_AMOXICILINA}
- HIDRATACIÓN ORAL Y MEDIDAS GENERALES.
- CONTROL CLÍNICO SEGÚN EVOLUCIÓN; REVALORAR ANTES SI PERSISTE FIEBRE, DOLOR O NO HAY MEJORÍA.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA: OTORREA, EDEMA O DOLOR RETROAURICULAR, DETERIORO DEL ESTADO GENERAL, VÓMITO PERSISTENTE, SIGNOS NEUROLÓGICOS O DIFICULTAD RESPIRATORIA.""",
        signos={"ta": "90/55", "fc": "118", "fr": "26", "sat": "98", "temp": "38.4", "peso": "12.5", "talla": "88", "pc": "48", "pb": "14.5"},
        gpc="OTITIS", aiepi="FIEBRE", fecha_nacimiento=date(2024, 8, 20), sexo="Femenino",
        gpc_criterios={
            "OTOSCOPIA Y LATERALIDAD": "OTITIS MEDIA AGUDA DERECHA DOCUMENTADA POR OTOSCOPIA: MEMBRANA ERITEMATOSA, ABOMBADA Y CON MOVILIDAD DISMINUIDA.",
            "DOLOR, FIEBRE, OTORREA Y SIGNOS DE COMPLICACIÓN": "OTALGIA Y FIEBRE 38.6 °C; SIN OTORREA NI HALLAZGOS RETROAURICULARES.",
            "ANTIBIÓTICO / ANALGESIA Y SITIO DE MANEJO": "EGRESO POR BUEN ESTADO GENERAL Y TOLERANCIA ORAL; ANALGESIA Y AMOXICILINA SI CUMPLE CRITERIOS Y PROTOCOLO.",
            "SIGNOS DE ALARMA / CONTROL": "CONTROL SEGÚN EVOLUCIÓN Y RECONSULTA POR SIGNOS DE COMPLICACIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO Y ESTADO GENERAL": "AUSENTES; ALERTA, HIDRATADA Y HEMODINÁMICAMENTE ESTABLE.",
            "TIEMPO DE EVOLUCIÓN, TEMPERATURA Y FOCO CLÍNICO": "48 HORAS, FIEBRE HASTA 38.6 °C, FOCO OTOLÓGICO DERECHO DOCUMENTADO.",
            "EXANTEMA, RIGIDEZ DE CUELLO, PETEQUIAS U OTROS SIGNOS DE ALARMA SI APLICAN": "AUSENTES.",
            "EXÁMENES COMPLEMENTARIOS O JUSTIFICACIÓN DE NO SOLICITARLOS": "DIAGNÓSTICO CLÍNICO POR OTOSCOPIA; SIN PARACLÍNICOS DE RUTINA AL INGRESO.",
            "CONDUCTA, SIGNOS DE ALARMA Y CONTROL": "MANEJO AMBULATORIO, ANALGESIA, ANTIBIÓTICO SEGÚN CRITERIOS Y CONSEJERÍA DE RECONSULTA.",
        },
        justificacion="LA OTOSCOPIA CONFIRMA OTITIS MEDIA AGUDA SIN DATOS DE MASTOIDITIS, COMPROMISO NEUROLÓGICO NI DETERIORO GENERAL, POR LO QUE SE JUSTIFICA MANEJO AMBULATORIO CON CONTROL.",
    ),
}


EJEMPLOS_NEONATALES = {
    "Recién nacido sano - control": {
        "nombre": "CONTROL NEONATAL SIN SIGNOS DE ALARMA",
        "fecha_nacimiento": date(2026, 8, 18),
        "motivo": "CONTROL DEL RECIÉN NACIDO",
        "enfermedad": "RECIÉN NACIDO DE 10 DÍAS, EN CONTROL. LA MADRE REFIERE LACTANCIA EFECTIVA CADA 2 A 3 HORAS, DIURESIS Y DEPOSICIONES PRESENTES. NIEGA FIEBRE, RECHAZO ALIMENTARIO, VÓMITO VERDE, APNEAS, CIANOSIS O LETARGIA.",
        "antecedentes": "NEONATALES: RECIÉN NACIDO A TÉRMINO, PARTO VAGINAL SIN COMPLICACIONES, PESO AL NACER 3200 G. EGRESO CONJUNTO. TAMIZAJES Y VACUNACIÓN SEGÚN REGISTRO PERINATAL.",
        "revision": "ALIMENTACIÓN: LACTANCIA MATERNA EFECTIVA CADA 2 A 3 HORAS, SIN ATRAGANTAMIENTO, CIANOSIS O FATIGA DURANTE LA TOMA. DIGESTIVO: SIN VÓMITO VERDE, DISTENSIÓN ABDOMINAL NI SANGRE EN HECES. URINARIO: DIURESIS PRESENTE. NEUROLÓGICO: SIN LETARGIA, IRRITABILIDAD INCONSOLABLE, CONVULSIONES NI APNEAS. RESPIRATORIO: SIN QUEJIDO, TIRAJE, ALETEO NASAL, CIANOSIS O PAUSAS RESPIRATORIAS.",
        "examen": "RECIÉN NACIDO EN BUEN ESTADO GENERAL, ALERTA, NORMOHIDRATADO, AFEBRIL, CON BUENA PERFUSIÓN.\n\nCABEZA: NORMOCÉFALA, FONTANELA ANTERIOR NORMOTENSA, SIN CEFALOHEMATOMA.\nOJOS: CONJUNTIVAS ROSADAS, ESCLERAS ANICTÉRICAS, REFLEJO ROJO PRESENTE BILATERALMENTE.\nOÍDOS: PABELLONES SIN ALTERACIONES EVIDENTES.\nNARIZ: PERMEABLE BILATERALMENTE.\nOROFARINGE: MUCOSAS HÚMEDAS, PALADAR ÍNTEGRO, SUCCIÓN EFECTIVA.\nCUELLO: MÓVIL, SIN MASAS.\nTÓRAX: SIMÉTRICO, NORMOEXPANSIBLE, SIN TIRAJES.\nCARDIOPULMONAR: RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN QUEJIDO NI AGREGADOS.\nABDOMEN: NO DISTENDIDO, BLANDO, RSHS PRESENTES, CORDÓN UMBILICAL SIN SIGNOS DE INFECCIÓN.\nGENITALES: ACORDES AL SEXO, SIN ALTERACIONES EVIDENTES.\nEXTREMIDADES: SIMÉTRICAS, SIN EDEMAS, LLENADO CAPILAR MENOR DE 2 SEGUNDOS.\nNEUROLÓGICO: ALERTA, TONO ADECUADO, MORO, SUCCIÓN Y BÚSQUEDA PRESENTES, SIN DÉFICIT.\nPIEL: ROSADA, BIEN PERFUNDIDA, SIN LESIONES NI ICTERICIA CLÍNICAMENTE SIGNIFICATIVA.",
        "diagnostico": "CONTROL DEL RECIÉN NACIDO",
        "plan": """- CONTINUAR LACTANCIA MATERNA A LIBRE DEMANDA.
- VERIFICAR PESO Y GANANCIA PONDERAL EN EL CONTROL.
- SE BRINDA EDUCACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA NEONATALES Y CONTROL SEGÚN RUTA INTEGRAL.""",
        "signos": {"fc": "132", "fr": "40", "sat": "97", "temp": "36.7", "peso": "3.2", "talla": "50", "pc": "34"},
    },
    "Ictericia neonatal - valoración": {
        "nombre": "ICTERICIA NEONATAL - VALORACIÓN ESTRUCTURADA",
        "fecha_nacimiento": date(2026, 8, 24),
        "motivo": "COLORACIÓN AMARILLA DE PIEL",
        "enfermedad": "RECIÉN NACIDO DE 4 DÍAS CON COLORACIÓN AMARILLA PROGRESIVA. TOMA SENO MATERNO, CON DIURESIS PRESENTE. NIEGA LETARGIA, FIEBRE, VÓMITO VERDE, APNEAS O CIANOSIS. DOCUMENTAR EDAD EN HORAS, FACTORES DE RIESGO Y RESULTADO DE BILIRRUBINA SEGÚN DISPONIBILIDAD.",
        "antecedentes": "NEONATALES: DOCUMENTAR EDAD GESTACIONAL, GRUPO/RH MATERNO Y DEL RECIÉN NACIDO, PESO AL NACER, PÉRDIDA PONDERAL, TRAUMA DE PARTO, HERMANOS CON FOTOTERAPIA Y TAMIZAJES.",
        "revision": "ALIMENTACIÓN: DOCUMENTAR FRECUENCIA Y EFECTIVIDAD DE LACTANCIA, VÓMITO Y TOLERANCIA. ELIMINACIÓN: REGISTRAR MICCIONES Y DEPOSICIONES. NEUROLÓGICO: NIEGA LETARGIA, HIPERTONÍA, LLANTO AGUDO, APNEAS O CONVULSIONES. RESPIRATORIO: NIEGA CIANOSIS, QUEJIDO, TIRAJE O ALETEO NASAL. INFECCIOSO: NIEGA FIEBRE O HIPOTERMIA. DOCUMENTAR FACTORES DE RIESGO PARA HIPERBILIRRUBINEMIA.",
        "examen": "RECIÉN NACIDO ALERTA, HEMODINÁMICAMENTE ESTABLE, NORMOHIDRATADO, AFEBRIL.\n\nCABEZA: NORMOCÉFALA, FONTANELA ANTERIOR NORMOTENSA, SIN CEFALOHEMATOMA.\nOJOS: CONJUNTIVAS ROSADAS, ESCLERAS SUBICTÉRICAS.\nOÍDOS: SIN ALTERACIONES EVIDENTES.\nNARIZ: PERMEABLE.\nOROFARINGE: MUCOSAS HÚMEDAS, SUCCIÓN EFECTIVA A VALORAR.\nCUELLO: MÓVIL, SIN MASAS.\nTÓRAX: SIMÉTRICO, NORMOEXPANSIBLE, SIN TIRAJES.\nCARDIOPULMONAR: RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN QUEJIDO NI AGREGADOS.\nABDOMEN: NO DISTENDIDO, BLANDO, RSHS PRESENTES, SIN HEPATOESPLENOMEGALIA CLÍNICA.\nGENITALES: ACORDES AL SEXO, SIN ALTERACIONES EVIDENTES.\nEXTREMIDADES: SIMÉTRICAS, SIN EDEMAS, LLENADO CAPILAR MENOR DE 2 SEGUNDOS.\nNEUROLÓGICO: ALERTA, TONO ADECUADO, MORO Y SUCCIÓN PRESENTES, SIN SIGNOS DE ENCEFALOPATÍA.\nPIEL: ICTERICIA CLÍNICA A CORRELACIONAR CON EDAD EN HORAS, BILIRRUBINA, EDAD GESTACIONAL Y FACTORES DE RIESGO; SIN PETEQUIAS NI LESIONES.",
        "diagnostico": "ICTERICIA NEONATAL EN ESTUDIO",
        "plan": """- CUANTIFICAR BILIRRUBINA Y UBICAR RESULTADO SEGÚN EDAD POSNATAL, EDAD GESTACIONAL Y FACTORES DE RIESGO.
- VERIFICAR EFECTIVIDAD DE LA ALIMENTACIÓN, PESO Y ELIMINACIÓN.
- DEFINIR FOTOTERAPIA, OBSERVACIÓN O REMISIÓN SEGÚN NOMOGRAMA Y PROTOCOLO INSTITUCIONAL.
- SE BRINDA INFORMACIÓN A PADRES O CUIDADOR RESPONSABLE SOBRE SIGNOS DE ALARMA Y PLAN DE CONTROL.""",
        "signos": {"fc": "138", "fr": "42", "sat": "97", "temp": "36.8", "peso": "3.0", "talla": "50", "pc": "34"},
    },
}


def nombres_ejemplos(familia="pediatria", conducta=None) -> list[str]:
    catalogo = EJEMPLOS_NEONATALES if familia == "neonatal" else EJEMPLOS_PEDIATRIA
    if conducta:
        return [nombre for nombre, caso in catalogo.items() if caso.get("conducta") == conducta]
    return list(catalogo)


def obtener_ejemplo(nombre: str, familia="pediatria") -> dict:
    catalogo = EJEMPLOS_NEONATALES if familia == "neonatal" else EJEMPLOS_PEDIATRIA
    return deepcopy(catalogo.get(nombre, {}))
