"""Casos docentes editables para documentar rutas pediátricas frecuentes.

Los ejemplos no sustituyen la valoración ni los protocolos institucionales. Se
cargan como punto de partida para que el profesional los adapte al paciente.
"""

from __future__ import annotations

from copy import deepcopy
from datetime import date


ANTECEDENTES_PEDIATRICOS = """NEONATALES: PRODUCTO DE SEGUNDA GESTACIÓN, EMBARAZO CONTROLADO, SIN COMPLICACIONES, NACE A TÉRMINO, SIN REQUERIMIENTO DE OXÍGENO U HOSPITALIZACIÓN, EGRESO CONJUNTO.
INMUNOLÓGICOS: VACUNAS AL DÍA SEGÚN PAI, SIN REACCIONES ATRIBUIDAS A VACUNAS.
ALIMENTACIÓN: ACORDE A LA EDAD.
PATOLÓGICOS, HOSPITALARIOS, FARMACOLÓGICOS, TRAUMÁTICOS, TÓXICOS, ALÉRGICOS, TRANSFUSIONALES Y QUIRÚRGICOS: NIEGA.
FAMILIARES: PADRE Y MADRE SANOS, NO CONSANGUÍNEOS.
PSICOSOCIALES: VIVIENDA CON TODOS LOS SERVICIOS, SIN EXPOSICIONES DE RIESGO RELEVANTES."""

REVISION_PEDIATRICA_COMPLETA = """CONSTITUCIONAL: SEGÚN CUADRO ACTUAL; SIN PÉRDIDA DE PESO DOCUMENTADA.
CARDIOVASCULAR: NIEGA CIANOSIS, SÍNCOPE, DOLOR PRECORDIAL O EDEMAS.
RESPIRATORIO: SÍNTOMAS Y HALLAZGOS DESCRITOS EN ENFERMEDAD ACTUAL Y EXAMEN FÍSICO; NIEGA APNEAS Y CIANOSIS.
DIGESTIVO: SEGÚN CUADRO ACTUAL; NIEGA HEMATEMESIS, HEMATOQUEZIA O MELENA.
URINARIO: DIURESIS SEGÚN CUADRO ACTUAL; NIEGA DISURIA, HEMATURIA O COLURIA.
NEUROLÓGICO: NIEGA CONVULSIONES, ALTERACIÓN DEL ESTADO DE CONCIENCIA O FOCALIZACIONES.
PIEL: NIEGA PETEQUIAS, EQUIMOSIS O LESIONES DIFERENTES A LAS DESCRITAS.
MÚSCULO-ESQUELÉTICO: NIEGA ARTRALGIAS, COJERA O EDEMAS."""


def _examen_pediatrico_completo(
    estado, *, nariz="PERMEABLE, SIN SECRECIONES.",
    orofaringe="MUCOSAS HÚMEDAS, SIN LESIONES.",
    torax="SIMÉTRICO, NORMOEXPANSIBLE, SIN TIRAJES.",
    cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN AGREGADOS PULMONARES.",
    abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, NO DOLOROSO, SIN SIGNOS DE IRRITACIÓN PERITONEAL.",
    piel="ROSADA, BIEN PERFUNDIDA, SIN LESIONES.",
):
    """Mantiene el examen por sistemas completo en cada caso docente."""
    return f"""{estado}

CABEZA: NORMOCÉFALA, SIN LESIONES.
OJOS: CONJUNTIVAS ROSADAS, ESCLERAS ANICTÉRICAS, PUPILAS ISOCÓRICAS Y REACTIVAS.
OÍDOS: SIN ALTERACIONES EVIDENTES.
NARIZ: {nariz}
OROFARINGE: {orofaringe}
CUELLO: MÓVIL, SIN ADENOPATÍAS.
TÓRAX: {torax}
CARDIOPULMONAR: {cardiopulmonar}
ABDOMEN: {abdomen}
GENITALES: ACORDES A LA EDAD, SIN ALTERACIONES EVIDENTES.
EXTREMIDADES: EUTRÓFICAS, SIMÉTRICAS, SIN EDEMAS, LLENADO CAPILAR MENOR DE 2 SEGUNDOS.
NEUROLÓGICO: ALERTA, SIN FOCALIZACIONES, SIN SIGNOS DE MENINGISMO, FUERZA Y TONO CONSERVADOS, SIN DÉFICIT.
PIEL: {piel}"""


def _caso(
    *, nombre, motivo, enfermedad, examen, diagnostico, busqueda, conducta,
    plan, signos, gpc="", aiepi="RESPIRATORIO", gpc_criterios=None,
    aiepi_criterios=None, antecedentes=ANTECEDENTES_PEDIATRICOS,
    revision=REVISION_PEDIATRICA_COMPLETA,
    fecha_nacimiento=date(2023, 1, 15), sexo="Femenino", justificacion="",
):
    cierres = {
        "EGRESO": (
            "POR EL ESTADO GENERAL CONSERVADO, LA ESTABILIDAD CLÍNICA Y LA "
            "AUSENCIA DE CRITERIOS ACTUALES DE HOSPITALIZACIÓN, SE DEFINE MANEJO "
            "AMBULATORIO. SE EXPLICAN AL CUIDADOR LAS MEDIDAS EN CASA, EL TRATAMIENTO "
            "INDICADO, LOS SIGNOS DE ALARMA Y LA OPORTUNIDAD DE RECONSULTA."
        ),
        "OBSERVACIÓN": (
            "SE DEFINE OBSERVACIÓN PEDIÁTRICA PARA VIGILANCIA CLÍNICA SERIADA, "
            "OBJETIVAR LA RESPUESTA AL MANEJO INICIAL Y REEVALUAR EL SITIO DE MANEJO. "
            "SE EXPLICA AL CUIDADOR EL MOTIVO DE LA OBSERVACIÓN, LOS HALLAZGOS A VIGILAR "
            "Y EL PLAN DE REVALORACIÓN."
        ),
        "HOSPITALIZACIÓN": (
            "POR LOS HALLAZGOS CLÍNICOS DESCRITOS Y EL RIESGO DE DETERIORO, SE JUSTIFICA "
            "HOSPITALIZACIÓN PEDIÁTRICA PARA TRATAMIENTO, MONITORIZACIÓN Y REVALORACIÓN "
            "CLÍNICA. SE EXPLICA AL CUIDADOR LA INDICACIÓN, EL PLAN TERAPÉUTICO Y LOS "
            "CRITERIOS DE EVOLUCIÓN."
        ),
    }
    analisis = (
        f"PACIENTE PEDIÁTRICO QUE CONSULTA POR {motivo}. {enfermedad} "
        f"{justificacion or 'LA VALORACIÓN CLÍNICA SE INTERPRETA EN CONJUNTO CON LOS SIGNOS VITALES, EL EXAMEN POR SISTEMAS Y LA EVOLUCIÓN.'} "
        f"{cierres.get(conducta, '')}"
    )
    return {
        "nombre": nombre,
        "fecha_nacimiento": fecha_nacimiento,
        "sexo": sexo,
        "motivo": motivo,
        "enfermedad": enfermedad,
        "antecedentes": antecedentes,
        "revision": revision,
        "examen": examen,
        "diagnostico": diagnostico,
        "busqueda_cie10": busqueda,
        "conducta": conducta,
        "plan": plan,
        "analisis": analisis,
        "signos": signos,
        "gpc": gpc,
        "aiepi": aiepi,
        "gpc_criterios": gpc_criterios or {},
        "aiepi_criterios": aiepi_criterios or {},
    }


EJEMPLOS_PEDIATRIA = {
    "IRA alta / rinofaringitis": _caso(
        nombre="IRA ALTA - MANEJO AMBULATORIO",
        motivo="FIEBRE Y TOS",
        enfermedad="CUADRO CLÍNICO DE 3 DÍAS DE EVOLUCIÓN CON TOS HÚMEDA, RINORREA HIALINA Y FIEBRE NO CUANTIFICADA, SIN PICO TÉRMICO DOCUMENTADO. MANTIENE BUEN ESTADO GENERAL, TOLERA VÍA ORAL Y PRESENTA DIURESIS CONSERVADA. NIEGA DIFICULTAD RESPIRATORIA, TIRAJE, RESPIRACIÓN RÁPIDA, CIANOSIS, APNEAS, ESTRIDOR, SIBILANCIAS, VÓMITO, DIARREA, CONVULSIONES O SOMNOLENCIA ANORMAL. SIN CONTACTO CON PACIENTES GRAVES; VACUNACIÓN AL DÍA SEGÚN REFIERE.",
        examen=_examen_pediatrico_completo(
            "PACIENTE EN BUEN ESTADO GENERAL, ALERTA, HIDRATADO, FEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            nariz="RINORREA HIALINA ESCASA, SIN ALETEO NASAL.",
            orofaringe="MUCOSAS HÚMEDAS, FARINGE LEVEMENTE ERITEMATOSA, SIN EXUDADO.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN SIBILANCIAS, ESTERTORES NI DIFICULTAD RESPIRATORIA.",
        ),
        diagnostico="J00 - NASOFARINGITIS AGUDA [RESFRIADO COMÚN]",
        busqueda="rinofaringitis aguda",
        conducta="EGRESO",
        plan="""- MANEJO SINTOMÁTICO SEGÚN PESO Y TOLERANCIA.
- LAVADOS NASALES CON SOLUCIÓN SALINA Y ADECUADA HIDRATACIÓN ORAL.
- EDUCACIÓN SOBRE SIGNOS DE ALARMA RESPIRATORIOS, TOLERANCIA ORAL Y RECONSULTA.
- CONTROL POR PEDIATRÍA SEGÚN EVOLUCIÓN.""",
        signos={"ta": "90/55", "fc": "110", "fr": "24", "sat": "97", "temp": "38.1", "peso": "16.2", "talla": "101", "pc": "50.5", "pb": "16"},
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 24 RPM, SIN DIFICULTAD RESPIRATORIA.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "AUSENTES.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 97% AL AIRE AMBIENTE; BUEN ESTADO GENERAL.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "IRA ALTA SIN SIGNOS DE GRAVEDAD; MANEJO AMBULATORIO Y SIGNOS DE ALARMA EXPLICADOS.",
        },
    ),
    "Neumonía no complicada - ambulatoria": _caso(
        nombre="NEUMONÍA NO COMPLICADA - MANEJO AMBULATORIO",
        motivo="TOS Y FIEBRE",
        enfermedad="CUADRO CLÍNICO DE 4 DÍAS DE EVOLUCIÓN CON TOS HÚMEDA, FIEBRE CUANTIFICADA HASTA 38.5 °C Y DISMINUCIÓN LEVE DEL APETITO. TOLERA VÍA ORAL, MANTIENE DIURESIS Y JUEGO ENTRE LOS PICOS FEBRILES. NIEGA RESPIRACIÓN RÁPIDA, TIRAJE, CIANOSIS, APNEAS, ESTRIDOR, SIBILANCIAS, VÓMITO DE TODO LO INGERIDO, CONVULSIONES O LETARGIA. SIN ANTIBIÓTICOS PREVIOS PARA EL CUADRO ACTUAL.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADO, FEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            nariz="PERMEABLE, CON RINORREA HIALINA ESCASA.",
            orofaringe="MUCOSAS HÚMEDAS, SIN EXUDADO.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR LEVEMENTE DISMINUIDO EN BASE DERECHA CON CREPITANTES FOCALES, SIN TIRAJES, CIANOSIS NI SIBILANCIAS.",
        ),
        diagnostico="J18 - NEUMONÍA, NO ESPECIFICADA",
        busqueda="neumonía",
        conducta="EGRESO",
        plan="""- AMOXICILINA VO 90 MG/KG/DÍA DIVIDIDA CADA 12 HORAS; AJUSTAR PRESENTACIÓN, DURACIÓN Y CONTRAINDICACIONES AL PROTOCOLO INSTITUCIONAL.
- MANEJO ANTIPIRÉTICO SEGÚN PESO SI FIEBRE O DOLOR.
- CONTROL CLÍNICO EN 48 A 72 HORAS O ANTES SI DETERIORO.
- SIGNOS DE ALARMA RESPIRATORIOS Y DE RECONSULTA EXPLICADOS.""",
        signos={"ta": "92/56", "fc": "118", "fr": "38", "sat": "96", "temp": "38.4", "peso": "14", "talla": "96", "pc": "49", "pb": "15.5"},
        gpc="NEUMONIA",
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "SIN TIRAJES, SIN CIANOSIS, ESTADO GENERAL CONSERVADO.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 96% AL AIRE AMBIENTE.",
            "DECISIÓN DE SITIO DE MANEJO": "MANEJO AMBULATORIO: TOLERA VÍA ORAL, SIN SIGNOS DE GRAVEDAD.",
            "SIGNOS DE ALARMA / CONTROL": "CONTROL EN 48-72 HORAS; RECONSULTAR POR TIRAJE, CIANOSIS, DETERIORO, INTOLERANCIA ORAL O PERSISTENCIA DE FIEBRE.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 38 RPM, SIN TIRAJES.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIN TIRAJE, ESTRIDOR NI SIBILANCIAS.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 96% AL AIRE AMBIENTE; PERFUSIÓN Y ESTADO GENERAL CONSERVADOS.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "NEUMONÍA SIN CRITERIOS CLÍNICOS DE GRAVEDAD; EGRESO CON ANTIBIÓTICO, CONTROL Y SIGNOS DE ALARMA.",
        },
    ),
    "Neumonía - hospitalización": _caso(
        nombre="NEUMONÍA CON CRITERIOS DE HOSPITALIZACIÓN",
        motivo="TOS, FIEBRE Y DIFICULTAD RESPIRATORIA",
        enfermedad="CUADRO DE 3 DÍAS DE EVOLUCIÓN CON FIEBRE HASTA 39 °C, TOS PRODUCTIVA Y AUMENTO PROGRESIVO DEL TRABAJO RESPIRATORIO. CUIDADOR REFIERE DISMINUCIÓN DE LA INGESTA ORAL Y DIURESIS MENOR A LA HABITUAL. NIEGA CONVULSIONES, LETARGIA, APNEAS Y CIANOSIS CENTRAL. SIN ASPIRACIÓN, TRAUMA NI INGESTA DE CUERPO EXTRAÑO. SE DOCUMENTA ESTADO VACUNAL Y TRATAMIENTO RECIBIDO PREVIO A LA CONSULTA.",
        examen=_examen_pediatrico_completo(
            "PACIENTE IRRITABLE, ALERTA, TAQUIPNEICO, CON HIDRATACIÓN LEVEMENTE DISMINUIDA Y FIEBRE.",
            nariz="PERMEABLE, SIN ALETEO NASAL MARCADO.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL LEVE A MODERADO.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR DISMINUIDO EN BASE IZQUIERDA CON CREPITANTES, SIN CIANOSIS CENTRAL.",
            piel="BIEN PERFUNDIDA, SIN PETEQUIAS NI EXANTEMA.",
        ),
        diagnostico="J18 - NEUMONÍA, NO ESPECIFICADA",
        busqueda="neumonía",
        conducta="HOSPITALIZACIÓN",
        plan="""- HOSPITALIZACIÓN PEDIÁTRICA Y VIGILANCIA CLÍNICA RESPIRATORIA.
- OXÍGENO SI REQUIERE, CON META DE SATURACIÓN SEGÚN ALTITUD Y PROTOCOLO INSTITUCIONAL.
- PENICILINA CRISTALINA 200.000 UI/KG/DÍA IV, DIVIDIDA CADA 4 A 6 HORAS, POR 7 DÍAS; AJUSTAR A PESO, FUNCIÓN RENAL Y PROTOCOLO INSTITUCIONAL.
- CONTROL DE TOLERANCIA ORAL, HIDRATACIÓN, DIURESIS Y SIGNOS VITALES.
- RADIOGRAFÍA DE TÓRAX Y PARACLÍNICOS DE EXTENSIÓN SEGÚN SEVERIDAD, EVOLUCIÓN Y DISPONIBILIDAD; DOCUMENTAR LA JUSTIFICACIÓN.""",
        signos={"ta": "88/52", "fc": "132", "fr": "48", "sat": "91", "temp": "39", "peso": "12", "talla": "90", "pc": "48", "pb": "14.5"},
        gpc="NEUMONIA",
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "TAQUIPNEA Y TIRAJE SUBCOSTAL; DISMINUCIÓN DE INGESTA ORAL.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 91% AL AIRE AMBIENTE.",
            "DECISIÓN DE SITIO DE MANEJO": "HOSPITALIZACIÓN POR COMPROMISO RESPIRATORIO E INTOLERANCIA RELATIVA A LA VÍA ORAL.",
            "SIGNOS DE ALARMA / CONTROL": "VIGILANCIA INTRAHOSPITALARIA, REVALORACIÓN RESPIRATORIA Y DE OXIGENACIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "NO CONVULSIONES NI LETARGIA; INGESTA DISMINUIDA.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 48 RPM CON TIRAJE SUBCOSTAL.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "TIRAJE SUBCOSTAL PRESENTE; SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 91% AL AIRE AMBIENTE; REQUIERE VIGILANCIA Y OXÍGENO SEGÚN RESPUESTA.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "MANEJO INTRAHOSPITALARIO POR CRITERIOS CLÍNICOS DE GRAVEDAD.",
        },
        justificacion="PRESENTA TAQUIPNEA, TIRAJE SUBCOSTAL, SATURACIÓN DE 91% AL AIRE AMBIENTE, DISMINUCIÓN DE LA INGESTA Y HALLAZGOS FOCALES PULMONARES, COMPATIBLES CON COMPROMISO RESPIRATORIO QUE REQUIERE MANEJO INTRAHOSPITALARIO.",
    ),
    "Bronquiolitis": _caso(
        nombre="BRONQUIOLITIS - OBSERVACIÓN",
        motivo="TOS Y RESPIRACIÓN RUIDOSA",
        enfermedad="LACTANTE DE 8 MESES CON 3 DÍAS DE CORIZA, RINORREA Y TOS, SEGUIDOS DE RESPIRACIÓN RUIDOSA. ES EL PRIMER EPISODIO SIBILANTE. LACTANCIA DISMINUIDA, PERO ACEPTA PEQUEÑAS TOMAS; DIURESIS PRESENTE, AUNQUE MENOR A LA HABITUAL. NIEGA APNEAS, CIANOSIS, LETARGIA, CONVULSIONES Y VÓMITO DE TODO LO INGERIDO. SIN ANTECEDENTE DE CARDIOPATÍA, DISPLASIA BRONCOPULMONAR, INMUNODEFICIENCIA O PREMATURIDAD DE ALTO RIESGO.",
        examen=_examen_pediatrico_completo(
            "LACTANTE ALERTA, REACTIVO, CON HIDRATACIÓN LEVEMENTE DISMINUIDA, AFEBRIL.",
            nariz="RINORREA HIALINA Y CONGESTIÓN NASAL.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL LEVE Y ESPIRACIÓN PROLONGADA.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR BILATERAL, CON SIBILANCIAS DIFUSAS, SIN CIANOSIS.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, NO DOLOROSO.",
        ),
        diagnostico="J21 - BRONQUIOLITIS AGUDA",
        busqueda="bronquiolitis",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y REVALORACIÓN CLÍNICA RESPIRATORIA.
- HIGIENE NASAL, OFRECER LÍQUIDOS O LACTANCIA FRACCIONADA Y VIGILAR DIURESIS.
- OXÍGENO SEGÚN SATURACIÓN, ALTITUD Y PROTOCOLO INSTITUCIONAL.
- NO INDICAR ANTIBIÓTICOS, BRONCODILATADORES O PARACLÍNICOS DE RUTINA SIN JUSTIFICACIÓN CLÍNICA.
- EDUCACIÓN DE SIGNOS DE ALARMA Y DEFINICIÓN DEL SITIO DE MANEJO SEGÚN REVALORACIÓN.""",
        signos={"ta": "", "fc": "138", "fr": "44", "sat": "92", "temp": "37.8", "peso": "8", "talla": "69", "pc": "44", "pb": "14"},
        gpc="BRONQUIOLITIS",
        fecha_nacimiento=date(2025, 12, 20),
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "TIRAJE SUBCOSTAL LEVE Y SIBILANCIAS; SIN APNEAS NI CIANOSIS.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 92% AL AIRE AMBIENTE.",
            "HIDRATACIÓN / TOLERANCIA ORAL": "LACTANCIA DISMINUIDA, ACEPTA PEQUEÑAS TOMAS; DIURESIS EN VIGILANCIA.",
            "SIGNOS DE ALARMA / RECONSULTA": "REVALORAR TRABAJO RESPIRATORIO, SATURACIÓN, INGESTA Y DIURESIS PARA DEFINIR EGRESO U HOSPITALIZACIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES; SIN APNEAS NI CIANOSIS.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 44 RPM, TIRAJE SUBCOSTAL LEVE.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "TIRAJE SUBCOSTAL LEVE Y SIBILANCIAS DIFUSAS; SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 92% AL AIRE AMBIENTE; REQUIERE OBSERVACIÓN Y REVALORACIÓN.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN POR TRABAJO RESPIRATORIO Y TOLERANCIA ORAL DISMINUIDA.",
        },
    ),
    "Asma / exacerbación broncoobstructiva": _caso(
        nombre="ASMA - EXACERBACIÓN LEVE A MODERADA",
        motivo="SIBILANCIAS Y TOS",
        enfermedad="PACIENTE CON ANTECEDENTE DE SIBILANCIAS RECURRENTES Y RESPUESTA PREVIA A BRONCODILATADOR, CONSULTA POR 24 HORAS DE TOS, SIBILANCIAS Y DISNEA LEVE. SIN FIEBRE, CIANOSIS, APNEAS, ALTERACIÓN DEL ESTADO DE CONCIENCIA, DOLOR TORÁCICO NI INTOLERANCIA A LA VÍA ORAL. REFIERE EXPOSICIÓN RECIENTE A CUADRO VIRAL; NIEGA EXPOSICIÓN A HUMO DE CIGARRILLO. DOCUMENTAR MEDICACIÓN PREVIA, TÉCNICA INHALATORIA, CONTROLADOR Y ESCALA DE SEVERIDAD.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HABLA EN FRASES, HIDRATADO, AFEBRIL, HEMODINÁMICAMENTE ESTABLE.",
            nariz="PERMEABLE, SIN RINORREA ACTIVA.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL LEVE Y ESPIRACIÓN PROLONGADA.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR DISMINUIDO DE FORMA DIFUSA, CON SIBILANCIAS BILATERALES, SIN CIANOSIS.",
        ),
        diagnostico="J45 - ASMA",
        busqueda="asma",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN Y REVALORACIÓN OBJETIVA DE SEVERIDAD Y RESPUESTA.
- BRONCODILATADOR INHALADO CON ESPACIADOR SEGÚN PESO, SEVERIDAD Y PROTOCOLO INSTITUCIONAL; DOCUMENTAR RESPUESTA.
- OXIMETRÍA SERIADA Y OXÍGENO SI REQUIERE.
- EDUCACIÓN SOBRE TÉCNICA INHALATORIA, SIGNOS DE ALARMA Y PLAN DE CONTROL.""",
        signos={"ta": "96/58", "fc": "124", "fr": "34", "sat": "94", "temp": "36.8", "peso": "18", "talla": "108", "pc": "", "pb": "16"},
        gpc="ASMA",
        fecha_nacimiento=date(2020, 3, 8),
        gpc_criterios={
            "SEVERIDAD / RESPUESTA": "SIBILANCIAS Y TIRAJE LEVE; REQUIERE ESCALA Y REVALORACIÓN POSTERIOR A BRONCODILATADOR.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 94% AL AIRE AMBIENTE.",
            "TÉCNICA O PLAN INHALATORIO": "SE INDICA INHALADOR CON ESPACIADOR Y EDUCACIÓN DE TÉCNICA.",
            "SIGNOS DE ALARMA / CONTROL": "REVALORAR RESPUESTA; EGRESO SOLO SI MEJORA Y SE EXPLICAN SIGNOS DE ALARMA.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 34 RPM, TIRAJE SUBCOSTAL LEVE.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIBILANCIAS BILATERALES, SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 94% AL AIRE AMBIENTE; REVALORAR DESPUÉS DEL TRATAMIENTO.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN PARA OBJETIVAR RESPUESTA Y DEFINIR EGRESO.",
        },
    ),
    "Asma - hospitalización": _caso(
        nombre="ASMA - EXACERBACIÓN CON CRITERIOS DE HOSPITALIZACIÓN",
        motivo="DISNEA Y SIBILANCIAS",
        enfermedad="PACIENTE CON ASMA CONOCIDA, QUIEN PRESENTA 24 HORAS DE TOS, SIBILANCIAS Y AUMENTO PROGRESIVO DEL TRABAJO RESPIRATORIO. RECIBIÓ SALBUTAMOL DOMICILIARIO SIN MEJORÍA SOSTENIDA. PRESENTA DIFICULTAD PARA HABLAR EN FRASES COMPLETAS Y DISMINUCIÓN DE LA INGESTA. NIEGA FIEBRE, ASPIRACIÓN DE CUERPO EXTRAÑO, CIANOSIS CENTRAL, APNEAS, CONVULSIONES O ALTERACIÓN DEL ESTADO DE CONCIENCIA. DOCUMENTAR TRATAMIENTO CONTROLADOR, ADHERENCIA, TÉCNICA INHALATORIA Y DESENCADENANTES.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, ANSIOSO, TAQUIPNEICO, CON HABLA ENTRECORTADA, HIDRATACIÓN CONSERVADA Y AFEBRIL.",
            nariz="PERMEABLE, SIN SECRECIONES ABUNDANTES.",
            torax="SIMÉTRICO, CON TIRAJE SUBCOSTAL E INTERCOSTAL MODERADO Y ESPIRACIÓN PROLONGADA.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS. MURMULLO VESICULAR GLOBALMENTE DISMINUIDO, CON SIBILANCIAS BILATERALES; SIN CIANOSIS CENTRAL.",
        ),
        diagnostico="J45 - ASMA",
        busqueda="asma",
        conducta="HOSPITALIZACIÓN",
        plan="""- HOSPITALIZACIÓN PEDIÁTRICA, OXIMETRÍA SERIADA Y OXÍGENO SEGÚN RESPUESTA, ALTITUD Y PROTOCOLO INSTITUCIONAL.
- SALBUTAMOL INHALADO CON ESPACIADOR SEGÚN GRAVEDAD; DOCUMENTAR NÚMERO DE INHALACIONES, FRECUENCIA Y RESPUESTA CLÍNICA. PARA 25 KG: 0.15 MG/KG/NEBULIZACIÓN EQUIVALE A 3.8 MG POR DOSIS, MÁXIMO 5 MG, SI SE INDICA LA VÍA NEBULIZADA.
- CORTICOIDE SISTÉMICO SEGÚN PESO, VÍA TOLERADA Y PROTOCOLO INSTITUCIONAL; DOCUMENTAR DOSIS, INTERVALO Y FECHA DE INICIO.
- REVALORACIÓN CLÍNICA Y ESCALA DE SEVERIDAD POSTERIOR A CADA CICLO DE BRONCODILATADOR.
- EDUCACIÓN A CUIDADORES SOBRE TÉCNICA INHALATORIA, DESENCADENANTES, SIGNOS DE ALARMA Y PLAN DE EGRESO CUANDO SE LOGRE ESTABILIZACIÓN.""",
        signos={"ta": "102/62", "fc": "142", "fr": "42", "sat": "89", "temp": "36.8", "peso": "25", "talla": "125", "pc": "", "pb": "18"},
        gpc="ASMA",
        fecha_nacimiento=date(2018, 10, 10),
        gpc_criterios={
            "SEVERIDAD / RESPUESTA": "TIRAJE MODERADO, HABLA ENTRECORTADA Y SIBILANCIAS DIFUSAS; REQUIERE TRATAMIENTO Y REVALORACIÓN SERIADA.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 89% AL AIRE AMBIENTE.",
            "TÉCNICA O PLAN INHALATORIO": "SE INDICA SALBUTAMOL CON ESPACIADOR/NEBULIZACIÓN SEGÚN RESPUESTA Y EDUCACIÓN A CUIDADOR.",
            "SIGNOS DE ALARMA / CONTROL": "VIGILANCIA INTRAHOSPITALARIA HASTA MEJORÍA DEL TRABAJO RESPIRATORIO, OXIGENACIÓN Y TOLERANCIA ORAL.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "SIN CONVULSIONES, LETARGIA NI INCAPACIDAD TOTAL PARA BEBER; INGESTA DISMINUIDA.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 42 RPM, TIRAJE SUBCOSTAL E INTERCOSTAL MODERADO.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIBILANCIAS BILATERALES, SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 89% AL AIRE AMBIENTE; REQUIERE OXÍGENO Y VIGILANCIA.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "HOSPITALIZACIÓN POR EXACERBACIÓN CON HIPOXEMIA, TRABAJO RESPIRATORIO Y RESPUESTA DOMICILIARIA INSUFICIENTE.",
        },
        justificacion="PRESENTA HIPOXEMIA, TIRAJE MODERADO, HABLA ENTRECORTADA Y SIBILANCIAS DIFUSAS DESPUÉS DE MANEJO DOMICILIARIO SIN MEJORÍA SOSTENIDA.",
    ),
    "Crup": _caso(
        nombre="CRUP - MANEJO Y OBSERVACIÓN",
        motivo="TOS PERRUNA Y ESTRIDOR",
        enfermedad="CUADRO DE 24 HORAS DE RINORREA, TOS PERRUNA Y DISFONÍA. ESTRIDOR SOLO AL LLANTO, AUSENTE EN REPOSO. TOLERA VÍA ORAL Y MANTIENE DIURESIS. NIEGA CIANOSIS, APNEAS, SIALORREA, DISFAGIA, POSICIÓN EN TRÍPODE, LETARGIA O INGESTA DE CUERPO EXTRAÑO. SIN EPISODIOS PREVIOS GRAVES DOCUMENTADOS.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, HIDRATADO, AFEBRIL, SIN SIGNOS GENERALES DE PELIGRO.",
            nariz="RINORREA HIALINA ESCASA.",
            orofaringe="MUCOSAS HÚMEDAS, SIN SIALORREA NI EXUDADO.",
            torax="SIMÉTRICO, NORMOEXPANSIBLE, SIN TIRAJES.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO. ESTRIDOR SOLO AL LLANTO, AUSENTE EN REPOSO; SIN SIBILANCIAS.",
        ),
        diagnostico="J05 - LARINGITIS OBSTRUCTIVA AGUDA [CRUP]",
        busqueda="crup",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN Y REVALORACIÓN DEL ESTRIDOR, TRABAJO RESPIRATORIO Y TOLERANCIA ORAL.
- CORTICOIDE SEGÚN PESO, SEVERIDAD Y PROTOCOLO INSTITUCIONAL.
- ADRENALINA NEBULIZADA SOLO SI LA SEVERIDAD CLÍNICA LO INDICA, CON PERÍODO DE OBSERVACIÓN POSTERIOR.
- EDUCACIÓN SOBRE SIGNOS DE ALARMA Y RECONSULTA.""",
        signos={"ta": "", "fc": "118", "fr": "28", "sat": "97", "temp": "37.8", "peso": "13", "talla": "92", "pc": "48", "pb": "15"},
        gpc="CRUP",
        fecha_nacimiento=date(2023, 8, 10),
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "ESTRIDOR SOLO AL LLANTO, SIN TIRAJES NI CIANOSIS.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 97% AL AIRE AMBIENTE.",
            "REVALORACIÓN": "REVALORAR POSTERIOR A LA INTERVENCIÓN Y ANTES DEL EGRESO.",
            "SIGNOS DE ALARMA / RECONSULTA": "RECONSULTAR POR ESTRIDOR EN REPOSO, TIRAJE, CIANOSIS, LETARGIA O INTOLERANCIA ORAL.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 28 RPM, SIN TIRAJES.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "ESTRIDOR AL LLANTO, AUSENTE EN REPOSO; SIN SIBILANCIAS.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 97% AL AIRE AMBIENTE; PACIENTE ALERTA E HIDRATADO.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN PARA REVALORACIÓN CLÍNICA Y DEFINIR EGRESO.",
        },
    ),
    "EDA / deshidratación": _caso(
        nombre="EDA CON ALGUNA DESHIDRATACIÓN - OBSERVACIÓN",
        motivo="VÓMITO Y DIARREA",
        enfermedad="CUADRO DE 24 HORAS DE DEPOSICIONES LÍQUIDAS, SIN SANGRE, ASOCIADAS A VÓMITOS. ACEPTA PEQUEÑOS SORBOS, PERO PRESENTA DIURESIS DISMINUIDA. NIEGA LETARGIA, CONVULSIONES, VÓMITO DE TODO LO INGERIDO, HEMATOQUEZIA, DISTENSIÓN ABDOMINAL PROGRESIVA O DOLOR ABDOMINAL INTENSO. SE INTERROGA NÚMERO DE DEPOSICIONES, CONTACTOS, ALIMENTOS DE RIESGO, ANTIBIÓTICOS RECIENTES Y ESQUEMA DE VACUNACIÓN.",
        examen=_examen_pediatrico_completo(
            "PACIENTE IRRITABLE, ALERTA, CON ALGUNOS SIGNOS DE DESHIDRATACIÓN, AFEBRIL.",
            nariz="PERMEABLE, SIN SECRECIONES.",
            orofaringe="MUCOSAS SECAS, SIN LESIONES.",
            cardiopulmonar="RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN TIRAJES NI AGREGADOS.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, NO DOLOROSO, SIN MASAS NI SIGNOS DE IRRITACIÓN PERITONEAL.",
            piel="PIEL SIN LESIONES, PLIEGUE CUTÁNEO DE RETORNO LENTO, PERFUSIÓN CONSERVADA.",
        ),
        diagnostico="A09 - GASTROENTERITIS Y COLITIS DE ORIGEN NO ESPECIFICADO",
        busqueda="gastroenteritis",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y PLAN DE HIDRATACIÓN ORAL SEGÚN PESO Y CLASIFICACIÓN.
- CONTINUAR ALIMENTACIÓN SEGÚN TOLERANCIA, VIGILAR VÓMITO, DIURESIS Y SIGNOS VITALES.
- REVALORACIÓN CLÍNICA DEL ESTADO DE HIDRATACIÓN; DEFINIR EGRESO U HOSPITALIZACIÓN SEGÚN RESPUESTA.
- EDUCACIÓN DE SIGNOS DE ALARMA Y RECONSULTA.""",
        signos={"ta": "88/50", "fc": "128", "fr": "26", "sat": "98", "temp": "37.4", "peso": "12", "talla": "88", "pc": "48", "pb": "14.5"},
        gpc="EDA",
        aiepi="DIARREA",
        fecha_nacimiento=date(2024, 2, 20),
        gpc_criterios={
            "ESTADO DE HIDRATACIÓN": "ALGUNOS SIGNOS DE DESHIDRATACIÓN: MUCOSAS SECAS, OJOS LEVEMENTE HUNDIDOS Y PLIEGUE LENTO.",
            "TOLERANCIA ORAL / DIURESIS": "ACEPTA PEQUEÑOS SORBOS; DIURESIS DISMINUIDA EN VIGILANCIA.",
            "DECISIÓN DE SITIO DE MANEJO": "OBSERVACIÓN PARA PLAN DE HIDRATACIÓN Y REVALORACIÓN CLÍNICA.",
            "SIGNOS DE ALARMA / RECONSULTA": "RECONSULTAR POR LETARGIA, INTOLERANCIA TOTAL A VÍA ORAL, SANGRE EN HECES, DIURESIS AUSENTE O DETERIORO.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES: SIN LETARGIA, CONVULSIONES NI VÓMITO DE TODO LO INGERIDO.",
            "DURACIÓN, CARACTERÍSTICAS DE LAS DEPOSICIONES Y SANGRE EN HECES": "24 HORAS DE DIARREA LÍQUIDA, SIN SANGRE.",
            "ESTADO DE HIDRATACIÓN, TOLERANCIA ORAL Y DIURESIS": "MUCOSAS SECAS, OJOS LEVEMENTE HUNDIDOS, PLIEGUE LENTO; TOLERA PEQUEÑOS SORBOS Y DIURESIS DISMINUIDA.",
            "PLAN DE HIDRATACIÓN, ALIMENTACIÓN Y REVALORACIÓN": "PLAN DE HIDRATACIÓN ORAL Y REVALORACIÓN EN OBSERVACIÓN.",
            "SIGNOS DE ALARMA Y RECONSULTA": "SIGNOS DE ALARMA EXPLICADOS A CUIDADOR.",
        },
    ),
    "EDA con disentería - observación y coproscópico": _caso(
        nombre="EDA CON SANGRE EN HECES - OBSERVACIÓN Y COPROSCÓPICO",
        motivo="DIARREA CON SANGRE",
        enfermedad="CUADRO DE 2 DÍAS DE EVOLUCIÓN CON DEPOSICIONES LÍQUIDAS FRECUENTES, DOS EPISODIOS CON ESTRÍAS DE SANGRE Y DOLOR ABDOMINAL TIPO CÓLICO. ACEPTA PEQUEÑOS SORBOS, CON DIURESIS DISMINUIDA. NIEGA LETARGIA, CONVULSIONES, DISTENSIÓN ABDOMINAL PROGRESIVA, VÓMITO BILIOSO O VÓMITO DE TODO LO INGERIDO. SE DOCUMENTAN CONTACTOS, ALIMENTOS DE RIESGO, USO RECIENTE DE ANTIBIÓTICOS Y ESTADO VACUNAL.",
        examen=_examen_pediatrico_completo(
            "PACIENTE ALERTA, IRRITABLE, CON MUCOSAS LEVEMENTE SECAS, AFEBRIL Y PERFUSIÓN CONSERVADA.",
            orofaringe="MUCOSAS LEVEMENTE SECAS, SIN LESIONES.",
            abdomen="NO DISTENDIDO, RSHS PRESENTES, BLANDO, DOLOR LEVE DIFUSO A LA PALPACIÓN, SIN MASAS NI SIGNOS DE IRRITACIÓN PERITONEAL.",
        ),
        diagnostico="A09 - GASTROENTERITIS Y COLITIS DE ORIGEN NO ESPECIFICADO",
        busqueda="gastroenteritis",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y PLAN DE HIDRATACIÓN SEGÚN CLASIFICACIÓN CLÍNICA.
- COPROSCÓPICO Y ESTUDIOS COMPLEMENTARIOS SEGÚN HALLAZGOS, DADO EL REPORTE DE SANGRE EN HECES; DOCUMENTAR RESULTADOS Y SU IMPACTO EN LA CONDUCTA.
- CONTINUAR ALIMENTACIÓN SEGÚN TOLERANCIA, VIGILAR DIURESIS, NÚMERO Y CARACTERÍSTICAS DE LAS DEPOSICIONES.
- REVALORAR ESTADO DE HIDRATACIÓN Y EXAMEN ABDOMINAL PARA DEFINIR EGRESO, HOSPITALIZACIÓN O REMISIÓN.
- EXPLICAR A CUIDADOR SIGNOS DE ALARMA: LETARGIA, INTOLERANCIA TOTAL A VÍA ORAL, OLIGURIA/ANURIA, SANGRE ABUNDANTE, DOLOR INTENSO O DISTENSIÓN PROGRESIVA.""",
        signos={"ta": "90/54", "fc": "122", "fr": "25", "sat": "98", "temp": "37.5", "peso": "14", "talla": "96", "pc": "49", "pb": "15"},
        gpc="EDA", aiepi="DIARREA", fecha_nacimiento=date(2022, 5, 1),
        gpc_criterios={
            "ESTADO DE HIDRATACIÓN": "MUCOSAS LEVEMENTE SECAS, PERFUSIÓN CONSERVADA; REQUIERE REVALORACIÓN SERIADA.",
            "TOLERANCIA ORAL / DIURESIS": "ACEPTA PEQUEÑOS SORBOS; DIURESIS DISMINUIDA.",
            "DECISIÓN DE SITIO DE MANEJO": "OBSERVACIÓN POR DIARREA CON SANGRE, TOLERANCIA ORAL PARCIAL Y NECESIDAD DE REVALORACIÓN.",
            "SIGNOS DE ALARMA / RECONSULTA": "SIGNOS DE ALARMA DIGESTIVOS E HIDRATACIÓN EXPLICADOS AL CUIDADOR.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES: SIN LETARGIA, CONVULSIONES NI VÓMITO DE TODO LO INGERIDO.",
            "DURACIÓN, CARACTERÍSTICAS DE LAS DEPOSICIONES Y SANGRE EN HECES": "2 DÍAS DE DIARREA; DOS EPISODIOS CON ESTRÍAS DE SANGRE.",
            "ESTADO DE HIDRATACIÓN, TOLERANCIA ORAL Y DIURESIS": "MUCOSAS LEVEMENTE SECAS, TOLERA PEQUEÑOS SORBOS, DIURESIS DISMINUIDA.",
            "PLAN DE HIDRATACIÓN, ALIMENTACIÓN Y REVALORACIÓN": "HIDRATACIÓN, ALIMENTACIÓN SEGÚN TOLERANCIA Y REVALORACIÓN EN OBSERVACIÓN.",
            "SIGNOS DE ALARMA Y RECONSULTA": "SE EXPLICAN SIGNOS DE DETERIORO, SANGRE ABUNDANTE, OLIGURIA Y DOLOR ABDOMINAL INTENSO.",
        },
        justificacion="EL REPORTE DE SANGRE EN HECES, LA TOLERANCIA ORAL PARCIAL Y LA DIURESIS DISMINUIDA JUSTIFICAN OBSERVACIÓN, HIDRATACIÓN Y ESTUDIO DE HECES SEGÚN EL CONTEXTO CLÍNICO.",
    ),
}


EJEMPLOS_NEONATALES = {
    "Recién nacido sano - control": {
        "nombre": "CONTROL NEONATAL SIN SIGNOS DE ALARMA",
        "fecha_nacimiento": date(2026, 8, 18),
        "motivo": "CONTROL DEL RECIÉN NACIDO",
        "enfermedad": "RECIÉN NACIDO DE 10 DÍAS, EN CONTROL. LA MADRE REFIERE LACTANCIA EFECTIVA CADA 2 A 3 HORAS, DIURESIS Y DEPOSICIONES PRESENTES. NIEGA FIEBRE, RECHAZO ALIMENTARIO, VÓMITO VERDE, APNEAS, CIANOSIS O LETARGIA.",
        "antecedentes": "NEONATALES: RECIÉN NACIDO A TÉRMINO, PARTO VAGINAL SIN COMPLICACIONES, PESO AL NACER 3200 G. EGRESO CONJUNTO. TAMIZAJES Y VACUNACIÓN SEGÚN REGISTRO PERINATAL.",
        "revision": "ALIMENTACIÓN: LACTANCIA MATERNA EFECTIVA CADA 2 A 3 HORAS, SIN ATRAGANTAMIENTO, CIANOSIS O FATIGA DURANTE LA TOMA. DIGESTIVO: SIN VÓMITO VERDE, DISTENSIÓN ABDOMINAL NI SANGRE EN HECES. URINARIO: DIURESIS PRESENTE. NEUROLÓGICO: SIN LETARGIA, IRRITABILIDAD INCONSOLABLE, CONVULSIONES NI APNEAS. RESPIRATORIO: SIN QUEJIDO, TIRAJE, ALETEO NASAL, CIANOSIS O PAUSAS RESPIRATORIAS.",
        "examen": "RECIÉN NACIDO EN BUEN ESTADO GENERAL, ALERTA, NORMOHIDRATADO, AFEBRIL, CON BUENA PERFUSIÓN.\n\nCABEZA: NORMOCÉFALA, FONTANELA ANTERIOR NORMOTENSA, SIN CEFALOHEMATOMA.\nOJOS: CONJUNTIVAS ROSADAS, ESCLERAS ANICTÉRICAS, REFLEJO ROJO PRESENTE BILATERALMENTE.\nOÍDOS: PABELLONES SIN ALTERACIONES EVIDENTES.\nNARIZ: PERMEABLE BILATERALMENTE.\nOROFARINGE: MUCOSAS HÚMEDAS, PALADAR ÍNTEGRO, SUCCIÓN EFECTIVA.\nCUELLO: MÓVIL, SIN MASAS.\nTÓRAX: SIMÉTRICO, NORMOEXPANSIBLE, SIN TIRAJES.\nCARDIOPULMONAR: RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN QUEJIDO NI AGREGADOS.\nABDOMEN: NO DISTENDIDO, BLANDO, RSHS PRESENTES, CORDÓN UMBILICAL SIN SIGNOS DE INFECCIÓN.\nGENITALES: ACORDES AL SEXO, SIN ALTERACIONES EVIDENTES.\nEXTREMIDADES: SIMÉTRICAS, SIN EDEMAS, LLENADO CAPILAR MENOR DE 2 SEGUNDOS.\nNEUROLÓGICO: ALERTA, TONO ADECUADO, MORO, SUCCIÓN Y BÚSQUEDA PRESENTES, SIN DÉFICIT.\nPIEL: ROSADA, BIEN PERFUNDIDA, SIN LESIONES NI ICTERICIA CLÍNICAMENTE SIGNIFICATIVA.",
        "diagnostico": "CONTROL DEL RECIÉN NACIDO",
        "plan": """- CONTINUAR LACTANCIA MATERNA A LIBRE DEMANDA.
- VERIFICAR PESO Y GANANCIA PONDERAL EN EL CONTROL.
- EDUCACIÓN SOBRE SIGNOS DE ALARMA NEONATALES Y CONTROL SEGÚN RUTA INTEGRAL.""",
        "signos": {"fc": "132", "fr": "40", "sat": "97", "temp": "36.7", "peso": "3.2", "talla": "50", "pc": "34"},
    },
    "Ictericia neonatal - valoración": {
        "nombre": "ICTERICIA NEONATAL - VALORACIÓN ESTRUCTURADA",
        "fecha_nacimiento": date(2026, 8, 24),
        "motivo": "COLORACIÓN AMARILLA DE PIEL",
        "enfermedad": "RECIÉN NACIDO DE 4 DÍAS CON COLORACIÓN AMARILLA PROGRESIVA. TOMA SENO MATERNO, CON DIURESIS PRESENTE. NIEGA LETARGIA, FIEBRE, VÓMITO VERDE, APNEAS O CIANOSIS. DOCUMENTAR EDAD EN HORAS, FACTORES DE RIESGO Y RESULTADO DE BILIRRUBINA SEGÚN DISPONIBILIDAD.",
        "antecedentes": "NEONATALES: DOCUMENTAR EDAD GESTACIONAL, GRUPO/RH MATERNO Y DEL RECIÉN NACIDO, PESO AL NACER, PÉRDIDA PONDERAL, TRAUMA DE PARTO, HERMANOS CON FOTOTERAPIA Y TAMIZAJES.",
        "revision": "ALIMENTACIÓN: DOCUMENTAR FRECUENCIA Y EFECTIVIDAD DE LACTANCIA, VÓMITO Y TOLERANCIA. ELIMINACIÓN: REGISTRAR MICCIONES Y DEPOSICIONES. NEUROLÓGICO: NIEGA LETARGIA, HIPERTONÍA, LLANTO AGUDO, APNEAS O CONVULSIONES. RESPIRATORIO: NIEGA CIANOSIS, QUEJIDO, TIRAJE O ALETEO NASAL. INFECCIOSO: NIEGA FIEBRE O HIPOTERMIA. DOCUMENTAR FACTORES DE RIESGO PARA HIPERBILIRRUBINEMIA.",
        "examen": "RECIÉN NACIDO ALERTA, HEMODINÁMICAMENTE ESTABLE, NORMOHIDRATADO, AFEBRIL.\n\nCABEZA: NORMOCÉFALA, FONTANELA ANTERIOR NORMOTENSA, SIN CEFALOHEMATOMA.\nOJOS: CONJUNTIVAS ROSADAS, ESCLERAS SUBICTÉRICAS.\nOÍDOS: SIN ALTERACIONES EVIDENTES.\nNARIZ: PERMEABLE.\nOROFARINGE: MUCOSAS HÚMEDAS, SUCCIÓN EFECTIVA A VALORAR.\nCUELLO: MÓVIL, SIN MASAS.\nTÓRAX: SIMÉTRICO, NORMOEXPANSIBLE, SIN TIRAJES.\nCARDIOPULMONAR: RUIDOS CARDÍACOS RÍTMICOS, SIN SOPLOS, MURMULLO VESICULAR CONSERVADO, SIN QUEJIDO NI AGREGADOS.\nABDOMEN: NO DISTENDIDO, BLANDO, RSHS PRESENTES, SIN HEPATOESPLENOMEGALIA CLÍNICA.\nGENITALES: ACORDES AL SEXO, SIN ALTERACIONES EVIDENTES.\nEXTREMIDADES: SIMÉTRICAS, SIN EDEMAS, LLENADO CAPILAR MENOR DE 2 SEGUNDOS.\nNEUROLÓGICO: ALERTA, TONO ADECUADO, MORO Y SUCCIÓN PRESENTES, SIN SIGNOS DE ENCEFALOPATÍA.\nPIEL: ICTERICIA CLÍNICA A CORRELACIONAR CON EDAD EN HORAS, BILIRRUBINA, EDAD GESTACIONAL Y FACTORES DE RIESGO; SIN PETEQUIAS NI LESIONES.",
        "diagnostico": "ICTERICIA NEONATAL EN ESTUDIO",
        "plan": """- CUANTIFICAR BILIRRUBINA Y UBICAR RESULTADO SEGÚN EDAD POSNATAL, EDAD GESTACIONAL Y FACTORES DE RIESGO.
- VERIFICAR EFECTIVIDAD DE LA ALIMENTACIÓN, PESO Y ELIMINACIÓN.
- DEFINIR FOTOTERAPIA, OBSERVACIÓN O REMISIÓN SEGÚN NOMOGRAMA Y PROTOCOLO INSTITUCIONAL.
- EXPLICAR SIGNOS DE ALARMA Y PLAN DE CONTROL A LOS CUIDADORES.""",
        "signos": {"fc": "138", "fr": "42", "sat": "97", "temp": "36.8", "peso": "3.0", "talla": "50", "pc": "34"},
    },
}


def nombres_ejemplos(familia="pediatria", conducta=None) -> list[str]:
    catalogo = EJEMPLOS_NEONATALES if familia == "neonatal" else EJEMPLOS_PEDIATRIA
    if conducta:
        return [nombre for nombre, caso in catalogo.items() if caso.get("conducta") == conducta]
    return list(catalogo)


def obtener_ejemplo(nombre: str, familia="pediatria") -> dict:
    catalogo = EJEMPLOS_NEONATALES if familia == "neonatal" else EJEMPLOS_PEDIATRIA
    return deepcopy(catalogo.get(nombre, {}))
