"""Casos docentes editables para documentar rutas pediátricas frecuentes.

Los ejemplos no sustituyen la valoración ni los protocolos institucionales. Se
cargan como punto de partida para que el profesional los adapte al paciente.
"""

from __future__ import annotations

from copy import deepcopy
from datetime import date


ANTECEDENTES_PEDIATRICOS = """NEONATALES: PRODUCTO DE SEGUNDA GESTACIÓN, EMBARAZO CONTROLADO, SIN COMPLICACIONES, NACE A TÉRMINO, SIN REQUERIMIENTO DE OXÍGENO U HOSPITALIZACIÓN, EGRESO CONJUNTO.
INMUNOLÓGICOS: VACUNAS AL DÍA SEGÚN PAI, SIN REACCIONES ATRIBUIDAS A VACUNAS.
ALIMENTACIÓN: ACORDE A LA EDAD.
PATOLÓGICOS, HOSPITALARIOS, FARMACOLÓGICOS, TRAUMÁTICOS, TÓXICOS, ALÉRGICOS, TRANSFUSIONALES Y QUIRÚRGICOS: NIEGA.
FAMILIARES: PADRE Y MADRE SANOS, NO CONSANGUÍNEOS.
PSICOSOCIALES: VIVIENDA CON TODOS LOS SERVICIOS, SIN EXPOSICIONES DE RIESGO RELEVANTES."""


def _caso(
    *, nombre, motivo, enfermedad, examen, diagnostico, busqueda, conducta,
    plan, signos, gpc="", aiepi="RESPIRATORIO", gpc_criterios=None,
    aiepi_criterios=None, antecedentes=ANTECEDENTES_PEDIATRICOS,
    fecha_nacimiento=date(2023, 1, 15), sexo="Femenino",
):
    return {
        "nombre": nombre,
        "fecha_nacimiento": fecha_nacimiento,
        "sexo": sexo,
        "motivo": motivo,
        "enfermedad": enfermedad,
        "antecedentes": antecedentes,
        "revision": "NIEGA OTROS SÍNTOMAS O SIGNOS DIFERENTES A LOS DESCRITOS EN LA ENFERMEDAD ACTUAL.",
        "examen": examen,
        "diagnostico": diagnostico,
        "busqueda_cie10": busqueda,
        "conducta": conducta,
        "plan": plan,
        "signos": signos,
        "gpc": gpc,
        "aiepi": aiepi,
        "gpc_criterios": gpc_criterios or {},
        "aiepi_criterios": aiepi_criterios or {},
    }


EJEMPLOS_PEDIATRIA = {
    "IRA alta / rinofaringitis": _caso(
        nombre="IRA ALTA - MANEJO AMBULATORIO",
        motivo="FIEBRE Y TOS",
        enfermedad="CUADRO CLÍNICO DE 3 DÍAS DE EVOLUCIÓN CON TOS HÚMEDA, RINORREA HIALINA Y FIEBRE NO CUANTIFICADA. TOLERA VÍA ORAL, DIURESIS CONSERVADA. NIEGA DIFICULTAD RESPIRATORIA, VÓMITO Y DIARREA.",
        examen="PACIENTE EN BUEN ESTADO GENERAL, ALERTA, HIDRATADO, FEBRIL. NARIZ CON RINORREA HIALINA. OROFARINGE LEVEMENTE ERITEMATOSA, SIN EXUDADO. TÓRAX SIMÉTRICO, SIN TIRAJES. MURMULLO VESICULAR CONSERVADO, SIN SIBILANCIAS NI ESTERTORES. ABDOMEN BLANDO, NO DOLOROSO. PIEL BIEN PERFUNDIDA, SIN EXANTEMA.",
        diagnostico="J00 - NASOFARINGITIS AGUDA [RESFRIADO COMÚN]",
        busqueda="rinofaringitis aguda",
        conducta="EGRESO",
        plan="""- MANEJO SINTOMÁTICO SEGÚN PESO Y TOLERANCIA.
- LAVADOS NASALES CON SOLUCIÓN SALINA Y ADECUADA HIDRATACIÓN ORAL.
- EDUCACIÓN SOBRE SIGNOS DE ALARMA RESPIRATORIOS, TOLERANCIA ORAL Y RECONSULTA.
- CONTROL POR PEDIATRÍA SEGÚN EVOLUCIÓN.""",
        signos={"ta": "90/55", "fc": "110", "fr": "24", "sat": "97", "temp": "38.1", "peso": "16.2", "talla": "101", "pc": "50.5", "pb": "16"},
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 24 RPM, SIN DIFICULTAD RESPIRATORIA.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "AUSENTES.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 97% AL AIRE AMBIENTE; BUEN ESTADO GENERAL.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "IRA ALTA SIN SIGNOS DE GRAVEDAD; MANEJO AMBULATORIO Y SIGNOS DE ALARMA EXPLICADOS.",
        },
    ),
    "Neumonía no complicada - ambulatoria": _caso(
        nombre="NEUMONÍA NO COMPLICADA - MANEJO AMBULATORIO",
        motivo="TOS Y FIEBRE",
        enfermedad="CUADRO CLÍNICO DE 4 DÍAS DE EVOLUCIÓN CON TOS HÚMEDA Y FIEBRE CUANTIFICADA. TOLERA VÍA ORAL Y MANTIENE DIURESIS. SIN CIANOSIS, APNEAS NI SIGNOS GENERALES DE PELIGRO.",
        examen="PACIENTE ALERTA, HIDRATADO, FEBRIL. TÓRAX SIMÉTRICO, SIN TIRAJES. MURMULLO VESICULAR DISMINUIDO EN BASE DERECHA CON CREPITANTES FOCALES. SIN CIANOSIS. ABDOMEN BLANDO, NO DOLOROSO. PIEL BIEN PERFUNDIDA.",
        diagnostico="J18 - NEUMONÍA, NO ESPECIFICADA",
        busqueda="neumonía",
        conducta="EGRESO",
        plan="""- AMOXICILINA VO 90 MG/KG/DÍA DIVIDIDA CADA 12 HORAS; AJUSTAR PRESENTACIÓN, DURACIÓN Y CONTRAINDICACIONES AL PROTOCOLO INSTITUCIONAL.
- MANEJO ANTIPIRÉTICO SEGÚN PESO SI FIEBRE O DOLOR.
- CONTROL CLÍNICO EN 48 A 72 HORAS O ANTES SI DETERIORO.
- SIGNOS DE ALARMA RESPIRATORIOS Y DE RECONSULTA EXPLICADOS.""",
        signos={"ta": "92/56", "fc": "118", "fr": "38", "sat": "96", "temp": "38.4", "peso": "14", "talla": "96", "pc": "49", "pb": "15.5"},
        gpc="NEUMONIA",
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "SIN TIRAJES, SIN CIANOSIS, ESTADO GENERAL CONSERVADO.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 96% AL AIRE AMBIENTE.",
            "DECISIÓN DE SITIO DE MANEJO": "MANEJO AMBULATORIO: TOLERA VÍA ORAL, SIN SIGNOS DE GRAVEDAD.",
            "SIGNOS DE ALARMA / CONTROL": "CONTROL EN 48-72 HORAS; RECONSULTAR POR TIRAJE, CIANOSIS, DETERIORO, INTOLERANCIA ORAL O PERSISTENCIA DE FIEBRE.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 38 RPM, SIN TIRAJES.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIN TIRAJE, ESTRIDOR NI SIBILANCIAS.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 96% AL AIRE AMBIENTE; PERFUSIÓN Y ESTADO GENERAL CONSERVADOS.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "NEUMONÍA SIN CRITERIOS CLÍNICOS DE GRAVEDAD; EGRESO CON ANTIBIÓTICO, CONTROL Y SIGNOS DE ALARMA.",
        },
    ),
    "Neumonía - hospitalización": _caso(
        nombre="NEUMONÍA CON CRITERIOS DE HOSPITALIZACIÓN",
        motivo="TOS, FIEBRE Y DIFICULTAD RESPIRATORIA",
        enfermedad="CUADRO DE 3 DÍAS DE EVOLUCIÓN CON FIEBRE, TOS PRODUCTIVA Y AUMENTO DEL TRABAJO RESPIRATORIO. DISMINUCIÓN DE LA INGESTA ORAL Y DIURESIS DISMINUIDA. SIN CONVULSIONES.",
        examen="PACIENTE IRRITABLE, TAQUIPNEICO, CON TIRAJE SUBCOSTAL LEVE A MODERADO. MURMULLO VESICULAR DISMINUIDO EN BASE IZQUIERDA CON CREPITANTES. SIN CIANOSIS CENTRAL. MUCOSAS SEMISECAS, PERFUSIÓN CONSERVADA.",
        diagnostico="J18 - NEUMONÍA, NO ESPECIFICADA",
        busqueda="neumonía",
        conducta="HOSPITALIZACIÓN",
        plan="""- HOSPITALIZACIÓN PEDIÁTRICA Y VIGILANCIA CLÍNICA RESPIRATORIA.
- OXÍGENO SI REQUIERE, CON META DE SATURACIÓN SEGÚN ALTITUD Y PROTOCOLO INSTITUCIONAL.
- ANTIBIÓTICO PARENTERAL SEGÚN PESO, SEVERIDAD Y GUÍA INSTITUCIONAL; DOCUMENTAR VÍA, DOSIS, INTERVALO Y FECHA DE INICIO.
- CONTROL DE TOLERANCIA ORAL, HIDRATACIÓN, DIURESIS Y SIGNOS VITALES.
- PARACLÍNICOS O IMÁGENES SOLO SEGÚN JUSTIFICACIÓN CLÍNICA.""",
        signos={"ta": "88/52", "fc": "132", "fr": "48", "sat": "91", "temp": "39", "peso": "12", "talla": "90", "pc": "48", "pb": "14.5"},
        gpc="NEUMONIA",
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "TAQUIPNEA Y TIRAJE SUBCOSTAL; DISMINUCIÓN DE INGESTA ORAL.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 91% AL AIRE AMBIENTE.",
            "DECISIÓN DE SITIO DE MANEJO": "HOSPITALIZACIÓN POR COMPROMISO RESPIRATORIO E INTOLERANCIA RELATIVA A LA VÍA ORAL.",
            "SIGNOS DE ALARMA / CONTROL": "VIGILANCIA INTRAHOSPITALARIA, REVALORACIÓN RESPIRATORIA Y DE OXIGENACIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "NO CONVULSIONES NI LETARGIA; INGESTA DISMINUIDA.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 48 RPM CON TIRAJE SUBCOSTAL.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "TIRAJE SUBCOSTAL PRESENTE; SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 91% AL AIRE AMBIENTE; REQUIERE VIGILANCIA Y OXÍGENO SEGÚN RESPUESTA.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "MANEJO INTRAHOSPITALARIO POR CRITERIOS CLÍNICOS DE GRAVEDAD.",
        },
    ),
    "Bronquiolitis": _caso(
        nombre="BRONQUIOLITIS - OBSERVACIÓN",
        motivo="TOS Y RESPIRACIÓN RUIDOSA",
        enfermedad="LACTANTE DE 8 MESES CON 3 DÍAS DE CORIZA Y TOS, SEGUIDOS DE RESPIRACIÓN RUIDOSA. LACTANCIA DISMINUIDA, PERO ACEPTA PEQUEÑAS TOMAS. SIN APNEAS NI CIANOSIS.",
        examen="LACTANTE ALERTA, HIDRATACIÓN LEVE DISMINUIDA. TÓRAX CON TIRAJE SUBCOSTAL LEVE, ESPIRACIÓN PROLONGADA Y SIBILANCIAS DIFUSAS. SIN CIANOSIS. ABDOMEN BLANDO, PERFUSIÓN CONSERVADA.",
        diagnostico="J21 - BRONQUIOLITIS AGUDA",
        busqueda="bronquiolitis",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y REVALORACIÓN CLÍNICA RESPIRATORIA.
- HIGIENE NASAL, OFRECER LÍQUIDOS O LACTANCIA FRACCIONADA Y VIGILAR DIURESIS.
- OXÍGENO SEGÚN SATURACIÓN, ALTITUD Y PROTOCOLO INSTITUCIONAL.
- NO INDICAR ANTIBIÓTICOS, BRONCODILATADORES O PARACLÍNICOS DE RUTINA SIN JUSTIFICACIÓN CLÍNICA.
- EDUCACIÓN DE SIGNOS DE ALARMA Y DEFINICIÓN DEL SITIO DE MANEJO SEGÚN REVALORACIÓN.""",
        signos={"ta": "", "fc": "138", "fr": "44", "sat": "92", "temp": "37.8", "peso": "8", "talla": "69", "pc": "44", "pb": "14"},
        gpc="BRONQUIOLITIS",
        fecha_nacimiento=date(2025, 12, 20),
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "TIRAJE SUBCOSTAL LEVE Y SIBILANCIAS; SIN APNEAS NI CIANOSIS.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 92% AL AIRE AMBIENTE.",
            "HIDRATACIÓN / TOLERANCIA ORAL": "LACTANCIA DISMINUIDA, ACEPTA PEQUEÑAS TOMAS; DIURESIS EN VIGILANCIA.",
            "SIGNOS DE ALARMA / RECONSULTA": "REVALORAR TRABAJO RESPIRATORIO, SATURACIÓN, INGESTA Y DIURESIS PARA DEFINIR EGRESO U HOSPITALIZACIÓN.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES; SIN APNEAS NI CIANOSIS.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 44 RPM, TIRAJE SUBCOSTAL LEVE.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "TIRAJE SUBCOSTAL LEVE Y SIBILANCIAS DIFUSAS; SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 92% AL AIRE AMBIENTE; REQUIERE OBSERVACIÓN Y REVALORACIÓN.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN POR TRABAJO RESPIRATORIO Y TOLERANCIA ORAL DISMINUIDA.",
        },
    ),
    "Asma / exacerbación broncoobstructiva": _caso(
        nombre="ASMA - EXACERBACIÓN LEVE A MODERADA",
        motivo="SIBILANCIAS Y TOS",
        enfermedad="PACIENTE CON ANTECEDENTE DE SIBILANCIAS RECURRENTES, CONSULTA POR 24 HORAS DE TOS, SIBILANCIAS Y DISNEA LEVE. SIN FIEBRE, CIANOSIS, APNEAS NI INTOLERANCIA A LA VÍA ORAL.",
        examen="PACIENTE ALERTA, HABLA EN FRASES. TÓRAX CON ESPIRACIÓN PROLONGADA Y SIBILANCIAS BILATERALES, TIRAJE SUBCOSTAL LEVE. SIN CIANOSIS. PERFUSIÓN CONSERVADA.",
        diagnostico="J45 - ASMA",
        busqueda="asma",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN Y REVALORACIÓN OBJETIVA DE SEVERIDAD Y RESPUESTA.
- BRONCODILATADOR INHALADO CON ESPACIADOR SEGÚN PESO, SEVERIDAD Y PROTOCOLO INSTITUCIONAL; DOCUMENTAR RESPUESTA.
- OXIMETRÍA SERIADA Y OXÍGENO SI REQUIERE.
- EDUCACIÓN SOBRE TÉCNICA INHALATORIA, SIGNOS DE ALARMA Y PLAN DE CONTROL.""",
        signos={"ta": "96/58", "fc": "124", "fr": "34", "sat": "94", "temp": "36.8", "peso": "18", "talla": "108", "pc": "", "pb": "16"},
        gpc="ASMA",
        fecha_nacimiento=date(2020, 3, 8),
        gpc_criterios={
            "SEVERIDAD / RESPUESTA": "SIBILANCIAS Y TIRAJE LEVE; REQUIERE ESCALA Y REVALORACIÓN POSTERIOR A BRONCODILATADOR.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 94% AL AIRE AMBIENTE.",
            "TÉCNICA O PLAN INHALATORIO": "SE INDICA INHALADOR CON ESPACIADOR Y EDUCACIÓN DE TÉCNICA.",
            "SIGNOS DE ALARMA / CONTROL": "REVALORAR RESPUESTA; EGRESO SOLO SI MEJORA Y SE EXPLICAN SIGNOS DE ALARMA.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 34 RPM, TIRAJE SUBCOSTAL LEVE.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "SIBILANCIAS BILATERALES, SIN ESTRIDOR.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 94% AL AIRE AMBIENTE; REVALORAR DESPUÉS DEL TRATAMIENTO.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN PARA OBJETIVAR RESPUESTA Y DEFINIR EGRESO.",
        },
    ),
    "Crup": _caso(
        nombre="CRUP - MANEJO Y OBSERVACIÓN",
        motivo="TOS PERRUNA Y ESTRIDOR",
        enfermedad="CUADRO DE 24 HORAS DE RINORREA, TOS PERRUNA Y DISFONÍA. ESTRIDOR SOLO AL LLANTO. TOLERA VÍA ORAL. SIN CIANOSIS, APNEAS NI SIALORREA.",
        examen="PACIENTE ALERTA, SIN SIGNOS GENERALES DE PELIGRO. ESTRIDOR AL LLANTO, SIN ESTRIDOR EN REPOSO. TÓRAX SIMÉTRICO, SIN TIRAJES. MURMULLO VESICULAR CONSERVADO. HIDRATADO.",
        diagnostico="J05 - LARINGITIS OBSTRUCTIVA AGUDA [CRUP]",
        busqueda="crup",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN Y REVALORACIÓN DEL ESTRIDOR, TRABAJO RESPIRATORIO Y TOLERANCIA ORAL.
- CORTICOIDE SEGÚN PESO, SEVERIDAD Y PROTOCOLO INSTITUCIONAL.
- ADRENALINA NEBULIZADA SOLO SI LA SEVERIDAD CLÍNICA LO INDICA, CON PERÍODO DE OBSERVACIÓN POSTERIOR.
- EDUCACIÓN SOBRE SIGNOS DE ALARMA Y RECONSULTA.""",
        signos={"ta": "", "fc": "118", "fr": "28", "sat": "97", "temp": "37.8", "peso": "13", "talla": "92", "pc": "48", "pb": "15"},
        gpc="CRUP",
        fecha_nacimiento=date(2023, 8, 10),
        gpc_criterios={
            "SEVERIDAD RESPIRATORIA": "ESTRIDOR SOLO AL LLANTO, SIN TIRAJES NI CIANOSIS.",
            "OXIMETRÍA DOCUMENTADA": "SPO2 97% AL AIRE AMBIENTE.",
            "REVALORACIÓN": "REVALORAR POSTERIOR A LA INTERVENCIÓN Y ANTES DEL EGRESO.",
            "SIGNOS DE ALARMA / RECONSULTA": "RECONSULTAR POR ESTRIDOR EN REPOSO, TIRAJE, CIANOSIS, LETARGIA O INTOLERANCIA ORAL.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES.",
            "FRECUENCIA RESPIRATORIA Y TRABAJO RESPIRATORIO": "FR 28 RPM, SIN TIRAJES.",
            "TIRAJE SUBCOSTAL, ESTRIDOR O SIBILANCIAS SEGÚN CORRESPONDA": "ESTRIDOR AL LLANTO, AUSENTE EN REPOSO; SIN SIBILANCIAS.",
            "OXIMETRÍA Y RESPUESTA CLÍNICA": "SPO2 97% AL AIRE AMBIENTE; PACIENTE ALERTA E HIDRATADO.",
            "CLASIFICACIÓN, SITIO DE MANEJO Y RECONSULTA": "OBSERVACIÓN PARA REVALORACIÓN CLÍNICA Y DEFINIR EGRESO.",
        },
    ),
    "EDA / deshidratación": _caso(
        nombre="EDA CON ALGUNA DESHIDRATACIÓN - OBSERVACIÓN",
        motivo="VÓMITO Y DIARREA",
        enfermedad="CUADRO DE 24 HORAS DE DEPOSICIONES LÍQUIDAS SIN SANGRE Y VÓMITOS. ACEPTA PEQUEÑOS SORBOS, CON DIURESIS DISMINUIDA. NO LETARGIA, NO CONVULSIONES, NO VÓMITO DE TODO LO INGERIDO.",
        examen="PACIENTE IRRITABLE, ALERTA. MUCOSAS SECAS, OJOS LEVEMENTE HUNDIDOS, PLIEGUE CUTÁNEO DE RETORNO LENTO. ABDOMEN BLANDO, SIN SIGNOS DE IRRITACIÓN PERITONEAL. PERFUSIÓN CONSERVADA.",
        diagnostico="A09 - GASTROENTERITIS Y COLITIS DE ORIGEN NO ESPECIFICADO",
        busqueda="gastroenteritis",
        conducta="OBSERVACIÓN",
        plan="""- OBSERVACIÓN PEDIÁTRICA Y PLAN DE HIDRATACIÓN ORAL SEGÚN PESO Y CLASIFICACIÓN.
- CONTINUAR ALIMENTACIÓN SEGÚN TOLERANCIA, VIGILAR VÓMITO, DIURESIS Y SIGNOS VITALES.
- REVALORACIÓN CLÍNICA DEL ESTADO DE HIDRATACIÓN; DEFINIR EGRESO U HOSPITALIZACIÓN SEGÚN RESPUESTA.
- EDUCACIÓN DE SIGNOS DE ALARMA Y RECONSULTA.""",
        signos={"ta": "88/50", "fc": "128", "fr": "26", "sat": "98", "temp": "37.4", "peso": "12", "talla": "88", "pc": "48", "pb": "14.5"},
        gpc="EDA",
        aiepi="DIARREA",
        fecha_nacimiento=date(2024, 2, 20),
        gpc_criterios={
            "ESTADO DE HIDRATACIÓN": "ALGUNOS SIGNOS DE DESHIDRATACIÓN: MUCOSAS SECAS, OJOS LEVEMENTE HUNDIDOS Y PLIEGUE LENTO.",
            "TOLERANCIA ORAL / DIURESIS": "ACEPTA PEQUEÑOS SORBOS; DIURESIS DISMINUIDA EN VIGILANCIA.",
            "DECISIÓN DE SITIO DE MANEJO": "OBSERVACIÓN PARA PLAN DE HIDRATACIÓN Y REVALORACIÓN CLÍNICA.",
            "SIGNOS DE ALARMA / RECONSULTA": "RECONSULTAR POR LETARGIA, INTOLERANCIA TOTAL A VÍA ORAL, SANGRE EN HECES, DIURESIS AUSENTE O DETERIORO.",
        },
        aiepi_criterios={
            "SIGNOS GENERALES DE PELIGRO": "AUSENTES: SIN LETARGIA, CONVULSIONES NI VÓMITO DE TODO LO INGERIDO.",
            "DURACIÓN, CARACTERÍSTICAS DE LAS DEPOSICIONES Y SANGRE EN HECES": "24 HORAS DE DIARREA LÍQUIDA, SIN SANGRE.",
            "ESTADO DE HIDRATACIÓN, TOLERANCIA ORAL Y DIURESIS": "MUCOSAS SECAS, OJOS LEVEMENTE HUNDIDOS, PLIEGUE LENTO; TOLERA PEQUEÑOS SORBOS Y DIURESIS DISMINUIDA.",
            "PLAN DE HIDRATACIÓN, ALIMENTACIÓN Y REVALORACIÓN": "PLAN DE HIDRATACIÓN ORAL Y REVALORACIÓN EN OBSERVACIÓN.",
            "SIGNOS DE ALARMA Y RECONSULTA": "SIGNOS DE ALARMA EXPLICADOS A CUIDADOR.",
        },
    ),
}


EJEMPLOS_NEONATALES = {
    "Recién nacido sano - control": {
        "nombre": "CONTROL NEONATAL SIN SIGNOS DE ALARMA",
        "fecha_nacimiento": date(2026, 8, 18),
        "motivo": "CONTROL DEL RECIÉN NACIDO",
        "enfermedad": "RECIÉN NACIDO DE 10 DÍAS, EN CONTROL. LA MADRE REFIERE LACTANCIA EFECTIVA CADA 2 A 3 HORAS, DIURESIS Y DEPOSICIONES PRESENTES. NIEGA FIEBRE, RECHAZO ALIMENTARIO, VÓMITO VERDE, APNEAS, CIANOSIS O LETARGIA.",
        "antecedentes": "NEONATALES: RECIÉN NACIDO A TÉRMINO, PARTO VAGINAL SIN COMPLICACIONES, PESO AL NACER 3200 G. EGRESO CONJUNTO. TAMIZAJES Y VACUNACIÓN SEGÚN REGISTRO PERINATAL.",
        "revision": "SIN SIGNOS DE ALARMA. LACTANCIA, DIURESIS Y DEPOSICIONES ACORDES A LA EDAD.",
        "examen": "RECIÉN NACIDO EN BUEN ESTADO GENERAL, ALERTA, NORMOHIDRATADO, AFEBRIL. FONTANELA ANTERIOR NORMOTENSA. CARDIOPULMONAR SIN HALLAZGOS PATOLÓGICOS EVIDENTES. ABDOMEN BLANDO. REFLEJOS DE MORO, SUCCIÓN Y BÚSQUEDA PRESENTES. PIEL ROSADA, SIN ICTERICIA CLÍNICAMENTE SIGNIFICATIVA.",
        "diagnostico": "CONTROL DEL RECIÉN NACIDO",
        "plan": """- CONTINUAR LACTANCIA MATERNA A LIBRE DEMANDA.
- VERIFICAR PESO Y GANANCIA PONDERAL EN EL CONTROL.
- EDUCACIÓN SOBRE SIGNOS DE ALARMA NEONATALES Y CONTROL SEGÚN RUTA INTEGRAL.""",
        "signos": {"fc": "132", "fr": "40", "sat": "97", "temp": "36.7", "peso": "3.2", "talla": "50", "pc": "34"},
    },
    "Ictericia neonatal - valoración": {
        "nombre": "ICTERICIA NEONATAL - VALORACIÓN ESTRUCTURADA",
        "fecha_nacimiento": date(2026, 8, 24),
        "motivo": "COLORACIÓN AMARILLA DE PIEL",
        "enfermedad": "RECIÉN NACIDO DE 4 DÍAS CON COLORACIÓN AMARILLA PROGRESIVA. TOMA SENO MATERNO, CON DIURESIS PRESENTE. NIEGA LETARGIA, FIEBRE, VÓMITO VERDE, APNEAS O CIANOSIS. DOCUMENTAR EDAD EN HORAS, FACTORES DE RIESGO Y RESULTADO DE BILIRRUBINA SEGÚN DISPONIBILIDAD.",
        "antecedentes": "NEONATALES: DOCUMENTAR EDAD GESTACIONAL, GRUPO/RH MATERNO Y DEL RECIÉN NACIDO, PESO AL NACER, PÉRDIDA PONDERAL, TRAUMA DE PARTO, HERMANOS CON FOTOTERAPIA Y TAMIZAJES.",
        "revision": "REGISTRAR ALIMENTACIÓN, NÚMERO DE MICCIONES Y DEPOSICIONES, SOMNOLENCIA, FIEBRE Y SIGNOS DE ENFERMEDAD.",
        "examen": "RECIÉN NACIDO ALERTA, HEMODINÁMICAMENTE ESTABLE. ICTERICIA CLÍNICA A CORRELACIONAR CON EDAD EN HORAS Y BILIRRUBINA. EVALUAR HIDRATACIÓN, CEFALOHEMATOMA, HEPATOESPLENOMEGALIA Y SIGNOS NEUROLÓGICOS.",
        "diagnostico": "ICTERICIA NEONATAL EN ESTUDIO",
        "plan": """- CUANTIFICAR BILIRRUBINA Y UBICAR RESULTADO SEGÚN EDAD POSNATAL, EDAD GESTACIONAL Y FACTORES DE RIESGO.
- VERIFICAR EFECTIVIDAD DE LA ALIMENTACIÓN, PESO Y ELIMINACIÓN.
- DEFINIR FOTOTERAPIA, OBSERVACIÓN O REMISIÓN SEGÚN NOMOGRAMA Y PROTOCOLO INSTITUCIONAL.
- EXPLICAR SIGNOS DE ALARMA Y PLAN DE CONTROL A LOS CUIDADORES.""",
        "signos": {"fc": "138", "fr": "42", "sat": "97", "temp": "36.8", "peso": "3.0", "talla": "50", "pc": "34"},
    },
}


def nombres_ejemplos(familia="pediatria") -> list[str]:
    catalogo = EJEMPLOS_NEONATALES if familia == "neonatal" else EJEMPLOS_PEDIATRIA
    return list(catalogo)


def obtener_ejemplo(nombre: str, familia="pediatria") -> dict:
    catalogo = EJEMPLOS_NEONATALES if familia == "neonatal" else EJEMPLOS_PEDIATRIA
    return deepcopy(catalogo.get(nombre, {}))
